// Auto-generated by scripts/build-docs-index.ts
// Do not edit manually - run: bun scripts/build-docs-index.ts

import type { LookupEntry } from './types';

export const lookupIndex: Record<string, LookupEntry> = {
	"getting started": {
		"keyword": "getting started",
		"slug": "01-hello-sine",
		"category": "tutorials",
		"title": "Hello Sine"
	},
	"first sound": {
		"keyword": "first sound",
		"slug": "01-hello-sine",
		"category": "tutorials",
		"title": "Hello Sine"
	},
	"sine": {
		"keyword": "sine",
		"slug": "01-hello-sine",
		"category": "tutorials",
		"title": "Hello Sine"
	},
	"oscillator": {
		"keyword": "oscillator",
		"slug": "01-hello-sine",
		"category": "tutorials",
		"title": "Hello Sine"
	},
	"output": {
		"keyword": "output",
		"slug": "01-hello-sine",
		"category": "tutorials",
		"title": "Hello Sine"
	},
	"beginner": {
		"keyword": "beginner",
		"slug": "01-hello-sine",
		"category": "tutorials",
		"title": "Hello Sine"
	},
	"tutorial": {
		"keyword": "tutorial",
		"slug": "01-hello-sine",
		"category": "tutorials",
		"title": "Hello Sine"
	},
	"pipe": {
		"keyword": "pipe",
		"slug": "pipes",
		"category": "language",
		"title": "Pipes & Holes"
	},
	"hole": {
		"keyword": "hole",
		"slug": "pipes",
		"category": "language",
		"title": "Pipes & Holes"
	},
	"|>": {
		"keyword": "|>",
		"slug": "pipes",
		"category": "language",
		"title": "Pipes & Holes"
	},
	"%": {
		"keyword": "%",
		"slug": "pipes",
		"category": "language",
		"title": "Pipes & Holes"
	},
	"signal flow": {
		"keyword": "signal flow",
		"slug": "pipes",
		"category": "language",
		"title": "Pipes & Holes"
	},
	"graph": {
		"keyword": "graph",
		"slug": "pipes",
		"category": "language",
		"title": "Pipes & Holes"
	},
	"connection": {
		"keyword": "connection",
		"slug": "pipes",
		"category": "language",
		"title": "Pipes & Holes"
	},
	"routing": {
		"keyword": "routing",
		"slug": "pipes",
		"category": "language",
		"title": "Pipes & Holes"
	},
	"lp": {
		"keyword": "lp",
		"slug": "filters",
		"category": "builtins",
		"title": "lp",
		"anchor": "lp"
	},
	"hp": {
		"keyword": "hp",
		"slug": "filters",
		"category": "builtins",
		"title": "hp",
		"anchor": "hp"
	},
	"bp": {
		"keyword": "bp",
		"slug": "filters",
		"category": "builtins",
		"title": "bp",
		"anchor": "bp"
	},
	"moog": {
		"keyword": "moog",
		"slug": "filters",
		"category": "builtins",
		"title": "moog",
		"anchor": "moog"
	},
	"filter": {
		"keyword": "filter",
		"slug": "filters",
		"category": "builtins",
		"title": "Filters"
	},
	"lowpass": {
		"keyword": "lowpass",
		"slug": "filters",
		"category": "builtins",
		"title": "Filters"
	},
	"highpass": {
		"keyword": "highpass",
		"slug": "filters",
		"category": "builtins",
		"title": "Filters"
	},
	"bandpass": {
		"keyword": "bandpass",
		"slug": "filters",
		"category": "builtins",
		"title": "Filters"
	},
	"svf": {
		"keyword": "svf",
		"slug": "filters",
		"category": "builtins",
		"title": "Filters"
	},
	"cutoff": {
		"keyword": "cutoff",
		"slug": "filters",
		"category": "builtins",
		"title": "Filters"
	},
	"resonance": {
		"keyword": "resonance",
		"slug": "filters",
		"category": "builtins",
		"title": "Filters"
	},
	"q": {
		"keyword": "q",
		"slug": "filters",
		"category": "builtins",
		"title": "Filters"
	},
	"out": {
		"keyword": "out",
		"slug": "utility",
		"category": "builtins",
		"title": "out",
		"anchor": "out"
	},
	"mtof": {
		"keyword": "mtof",
		"slug": "utility",
		"category": "builtins",
		"title": "mtof",
		"anchor": "mtof"
	},
	"dc": {
		"keyword": "dc",
		"slug": "utility",
		"category": "builtins",
		"title": "dc",
		"anchor": "dc"
	},
	"slew": {
		"keyword": "slew",
		"slug": "utility",
		"category": "builtins",
		"title": "slew",
		"anchor": "slew"
	},
	"sah": {
		"keyword": "sah",
		"slug": "utility",
		"category": "builtins",
		"title": "sah",
		"anchor": "sah"
	},
	"clock": {
		"keyword": "clock",
		"slug": "utility",
		"category": "builtins",
		"title": "clock",
		"anchor": "clock"
	},
	"utility": {
		"keyword": "utility",
		"slug": "utility",
		"category": "builtins",
		"title": "Utility"
	},
	"midi": {
		"keyword": "midi",
		"slug": "utility",
		"category": "builtins",
		"title": "Utility"
	},
	"frequency": {
		"keyword": "frequency",
		"slug": "utility",
		"category": "builtins",
		"title": "Utility"
	},
	"sample": {
		"keyword": "sample",
		"slug": "utility",
		"category": "builtins",
		"title": "Utility"
	},
	"hold": {
		"keyword": "hold",
		"slug": "utility",
		"category": "builtins",
		"title": "Utility"
	},
	"adsr": {
		"keyword": "adsr",
		"slug": "envelopes",
		"category": "builtins",
		"title": "adsr",
		"anchor": "adsr"
	},
	"ar": {
		"keyword": "ar",
		"slug": "envelopes",
		"category": "builtins",
		"title": "ar",
		"anchor": "ar"
	},
	"envelope": {
		"keyword": "envelope",
		"slug": "envelopes",
		"category": "builtins",
		"title": "Envelopes"
	},
	"attack": {
		"keyword": "attack",
		"slug": "envelopes",
		"category": "builtins",
		"title": "Envelopes"
	},
	"decay": {
		"keyword": "decay",
		"slug": "envelopes",
		"category": "builtins",
		"title": "Envelopes"
	},
	"sustain": {
		"keyword": "sustain",
		"slug": "envelopes",
		"category": "builtins",
		"title": "Envelopes"
	},
	"release": {
		"keyword": "release",
		"slug": "envelopes",
		"category": "builtins",
		"title": "Envelopes"
	},
	"gate": {
		"keyword": "gate",
		"slug": "envelopes",
		"category": "builtins",
		"title": "Envelopes"
	},
	"trigger": {
		"keyword": "trigger",
		"slug": "envelopes",
		"category": "builtins",
		"title": "Envelopes"
	},
	"sin": {
		"keyword": "sin",
		"slug": "oscillators",
		"category": "builtins",
		"title": "sin",
		"anchor": "sin"
	},
	"tri": {
		"keyword": "tri",
		"slug": "oscillators",
		"category": "builtins",
		"title": "tri",
		"anchor": "tri"
	},
	"saw": {
		"keyword": "saw",
		"slug": "oscillators",
		"category": "builtins",
		"title": "saw",
		"anchor": "saw"
	},
	"sqr": {
		"keyword": "sqr",
		"slug": "oscillators",
		"category": "builtins",
		"title": "sqr",
		"anchor": "sqr"
	},
	"phasor": {
		"keyword": "phasor",
		"slug": "oscillators",
		"category": "builtins",
		"title": "phasor",
		"anchor": "phasor"
	},
	"ramp": {
		"keyword": "ramp",
		"slug": "oscillators",
		"category": "builtins",
		"title": "ramp",
		"anchor": "ramp"
	},
	"noise": {
		"keyword": "noise",
		"slug": "oscillators",
		"category": "builtins",
		"title": "noise",
		"anchor": "noise"
	},
	"triangle": {
		"keyword": "triangle",
		"slug": "oscillators",
		"category": "builtins",
		"title": "Oscillators"
	},
	"sawtooth": {
		"keyword": "sawtooth",
		"slug": "oscillators",
		"category": "builtins",
		"title": "Oscillators"
	},
	"square": {
		"keyword": "square",
		"slug": "oscillators",
		"category": "builtins",
		"title": "Oscillators"
	},
	"waveform": {
		"keyword": "waveform",
		"slug": "oscillators",
		"category": "builtins",
		"title": "Oscillators"
	},
	"tone": {
		"keyword": "tone",
		"slug": "oscillators",
		"category": "builtins",
		"title": "Oscillators"
	},
	"contributing": {
		"keyword": "contributing",
		"slug": "DOCUMENTATION_GUIDE",
		"category": "concepts",
		"title": "Documentation Guide"
	},
	"documentation": {
		"keyword": "documentation",
		"slug": "DOCUMENTATION_GUIDE",
		"category": "concepts",
		"title": "Documentation Guide"
	},
	"guide": {
		"keyword": "guide",
		"slug": "DOCUMENTATION_GUIDE",
		"category": "concepts",
		"title": "Documentation Guide"
	},
	"standards": {
		"keyword": "standards",
		"slug": "DOCUMENTATION_GUIDE",
		"category": "concepts",
		"title": "Documentation Guide"
	}
};
