// Auto-generated by scripts/build-docs-index.ts
// Do not edit manually - run: bun scripts/build-docs-index.ts

import type { LookupEntry } from './types';

export const lookupIndex: Record<string, LookupEntry> = {
	"synthesis": {
		"keyword": "synthesis",
		"slug": "03-synthesis",
		"category": "tutorials",
		"title": "Building Synth Voices"
	},
	"synth": {
		"keyword": "synth",
		"slug": "03-synthesis",
		"category": "tutorials",
		"title": "Building Synth Voices"
	},
	"envelope": {
		"keyword": "envelope",
		"slug": "03-synthesis",
		"category": "tutorials",
		"title": "Building Synth Voices"
	},
	"adsr": {
		"keyword": "adsr",
		"slug": "envelopes",
		"category": "builtins",
		"title": "adsr",
		"anchor": "adsr"
	},
	"ar": {
		"keyword": "ar",
		"slug": "envelopes",
		"category": "builtins",
		"title": "ar",
		"anchor": "ar"
	},
	"subtractive": {
		"keyword": "subtractive",
		"slug": "03-synthesis",
		"category": "tutorials",
		"title": "Building Synth Voices"
	},
	"tutorial": {
		"keyword": "tutorial",
		"slug": "03-synthesis",
		"category": "tutorials",
		"title": "Building Synth Voices"
	},
	"voice": {
		"keyword": "voice",
		"slug": "03-synthesis",
		"category": "tutorials",
		"title": "Building Synth Voices"
	},
	"filter": {
		"keyword": "filter",
		"slug": "02-filters",
		"category": "tutorials",
		"title": "Shaping Sound with Filters"
	},
	"lowpass": {
		"keyword": "lowpass",
		"slug": "02-filters",
		"category": "tutorials",
		"title": "Shaping Sound with Filters"
	},
	"highpass": {
		"keyword": "highpass",
		"slug": "02-filters",
		"category": "tutorials",
		"title": "Shaping Sound with Filters"
	},
	"cutoff": {
		"keyword": "cutoff",
		"slug": "02-filters",
		"category": "tutorials",
		"title": "Shaping Sound with Filters"
	},
	"resonance": {
		"keyword": "resonance",
		"slug": "02-filters",
		"category": "tutorials",
		"title": "Shaping Sound with Filters"
	},
	"lp": {
		"keyword": "lp",
		"slug": "filters",
		"category": "builtins",
		"title": "lp",
		"anchor": "lp"
	},
	"hp": {
		"keyword": "hp",
		"slug": "filters",
		"category": "builtins",
		"title": "hp",
		"anchor": "hp"
	},
	"moog": {
		"keyword": "moog",
		"slug": "filters",
		"category": "builtins",
		"title": "moog",
		"anchor": "moog"
	},
	"rhythm": {
		"keyword": "rhythm",
		"slug": "04-rhythm",
		"category": "tutorials",
		"title": "Rhythm & Patterns"
	},
	"pattern": {
		"keyword": "pattern",
		"slug": "04-rhythm",
		"category": "tutorials",
		"title": "Rhythm & Patterns"
	},
	"beat": {
		"keyword": "beat",
		"slug": "04-rhythm",
		"category": "tutorials",
		"title": "Rhythm & Patterns"
	},
	"trigger": {
		"keyword": "trigger",
		"slug": "sequencing",
		"category": "builtins",
		"title": "trigger",
		"anchor": "trigger"
	},
	"euclidean": {
		"keyword": "euclidean",
		"slug": "04-rhythm",
		"category": "tutorials",
		"title": "Rhythm & Patterns"
	},
	"sequencer": {
		"keyword": "sequencer",
		"slug": "04-rhythm",
		"category": "tutorials",
		"title": "Rhythm & Patterns"
	},
	"clock": {
		"keyword": "clock",
		"slug": "utility",
		"category": "builtins",
		"title": "clock",
		"anchor": "clock"
	},
	"getting started": {
		"keyword": "getting started",
		"slug": "01-hello-sine",
		"category": "tutorials",
		"title": "Hello Sine"
	},
	"first sound": {
		"keyword": "first sound",
		"slug": "01-hello-sine",
		"category": "tutorials",
		"title": "Hello Sine"
	},
	"sine": {
		"keyword": "sine",
		"slug": "01-hello-sine",
		"category": "tutorials",
		"title": "Hello Sine"
	},
	"oscillator": {
		"keyword": "oscillator",
		"slug": "01-hello-sine",
		"category": "tutorials",
		"title": "Hello Sine"
	},
	"output": {
		"keyword": "output",
		"slug": "01-hello-sine",
		"category": "tutorials",
		"title": "Hello Sine"
	},
	"beginner": {
		"keyword": "beginner",
		"slug": "01-hello-sine",
		"category": "tutorials",
		"title": "Hello Sine"
	},
	"mini-notation": {
		"keyword": "mini-notation",
		"slug": "basics",
		"category": "mini-notation",
		"title": "Mini-Notation Basics"
	},
	"sequence": {
		"keyword": "sequence",
		"slug": "basics",
		"category": "mini-notation",
		"title": "Mini-Notation Basics"
	},
	"pitch": {
		"keyword": "pitch",
		"slug": "basics",
		"category": "mini-notation",
		"title": "Mini-Notation Basics"
	},
	"chord": {
		"keyword": "chord",
		"slug": "basics",
		"category": "mini-notation",
		"title": "Mini-Notation Basics"
	},
	"rest": {
		"keyword": "rest",
		"slug": "basics",
		"category": "mini-notation",
		"title": "Mini-Notation Basics"
	},
	"tidal": {
		"keyword": "tidal",
		"slug": "basics",
		"category": "mini-notation",
		"title": "Mini-Notation Basics"
	},
	"strudel": {
		"keyword": "strudel",
		"slug": "basics",
		"category": "mini-notation",
		"title": "Mini-Notation Basics"
	},
	"pipe": {
		"keyword": "pipe",
		"slug": "pipes",
		"category": "language",
		"title": "Pipes & Holes"
	},
	"hole": {
		"keyword": "hole",
		"slug": "pipes",
		"category": "language",
		"title": "Pipes & Holes"
	},
	"|>": {
		"keyword": "|>",
		"slug": "pipes",
		"category": "language",
		"title": "Pipes & Holes"
	},
	"%": {
		"keyword": "%",
		"slug": "pipes",
		"category": "language",
		"title": "Pipes & Holes"
	},
	"signal flow": {
		"keyword": "signal flow",
		"slug": "pipes",
		"category": "language",
		"title": "Pipes & Holes"
	},
	"graph": {
		"keyword": "graph",
		"slug": "pipes",
		"category": "language",
		"title": "Pipes & Holes"
	},
	"connection": {
		"keyword": "connection",
		"slug": "pipes",
		"category": "language",
		"title": "Pipes & Holes"
	},
	"routing": {
		"keyword": "routing",
		"slug": "pipes",
		"category": "language",
		"title": "Pipes & Holes"
	},
	"variables": {
		"keyword": "variables",
		"slug": "variables",
		"category": "language",
		"title": "Variables & Assignment"
	},
	"assignment": {
		"keyword": "assignment",
		"slug": "variables",
		"category": "language",
		"title": "Variables & Assignment"
	},
	"let": {
		"keyword": "let",
		"slug": "variables",
		"category": "language",
		"title": "Variables & Assignment"
	},
	"binding": {
		"keyword": "binding",
		"slug": "variables",
		"category": "language",
		"title": "Variables & Assignment"
	},
	"scope": {
		"keyword": "scope",
		"slug": "variables",
		"category": "language",
		"title": "Variables & Assignment"
	},
	"identifier": {
		"keyword": "identifier",
		"slug": "variables",
		"category": "language",
		"title": "Variables & Assignment"
	},
	"closures": {
		"keyword": "closures",
		"slug": "closures",
		"category": "language",
		"title": "Closures"
	},
	"functions": {
		"keyword": "functions",
		"slug": "closures",
		"category": "language",
		"title": "Closures"
	},
	"lambda": {
		"keyword": "lambda",
		"slug": "closures",
		"category": "language",
		"title": "Closures"
	},
	"anonymous": {
		"keyword": "anonymous",
		"slug": "closures",
		"category": "language",
		"title": "Closures"
	},
	"arrow": {
		"keyword": "arrow",
		"slug": "closures",
		"category": "language",
		"title": "Closures"
	},
	"callback": {
		"keyword": "callback",
		"slug": "closures",
		"category": "language",
		"title": "Closures"
	},
	"operators": {
		"keyword": "operators",
		"slug": "operators",
		"category": "language",
		"title": "Operators"
	},
	"precedence": {
		"keyword": "precedence",
		"slug": "operators",
		"category": "language",
		"title": "Operators"
	},
	"arithmetic": {
		"keyword": "arithmetic",
		"slug": "math",
		"category": "builtins",
		"title": "Arithmetic",
		"anchor": "arithmetic"
	},
	"plus": {
		"keyword": "plus",
		"slug": "operators",
		"category": "language",
		"title": "Operators"
	},
	"minus": {
		"keyword": "minus",
		"slug": "operators",
		"category": "language",
		"title": "Operators"
	},
	"multiply": {
		"keyword": "multiply",
		"slug": "operators",
		"category": "language",
		"title": "Operators"
	},
	"divide": {
		"keyword": "divide",
		"slug": "operators",
		"category": "language",
		"title": "Operators"
	},
	"power": {
		"keyword": "power",
		"slug": "operators",
		"category": "language",
		"title": "Operators"
	},
	"lfo": {
		"keyword": "lfo",
		"slug": "sequencing",
		"category": "builtins",
		"title": "lfo",
		"anchor": "lfo"
	},
	"euclid": {
		"keyword": "euclid",
		"slug": "sequencing",
		"category": "builtins",
		"title": "euclid",
		"anchor": "euclid"
	},
	"seq_step": {
		"keyword": "seq_step",
		"slug": "sequencing",
		"category": "builtins",
		"title": "seq_step",
		"anchor": "seq-step"
	},
	"timeline": {
		"keyword": "timeline",
		"slug": "sequencing",
		"category": "builtins",
		"title": "timeline",
		"anchor": "timeline"
	},
	"sequencing": {
		"keyword": "sequencing",
		"slug": "sequencing",
		"category": "builtins",
		"title": "Sequencing & Timing"
	},
	"timing": {
		"keyword": "timing",
		"slug": "sequencing",
		"category": "builtins",
		"title": "Sequencing & Timing"
	},
	"delay": {
		"keyword": "delay",
		"slug": "delays",
		"category": "builtins",
		"title": "delay",
		"anchor": "delay"
	},
	"echo": {
		"keyword": "echo",
		"slug": "delays",
		"category": "builtins",
		"title": "Delays"
	},
	"feedback": {
		"keyword": "feedback",
		"slug": "delays",
		"category": "builtins",
		"title": "Delays"
	},
	"time": {
		"keyword": "time",
		"slug": "delays",
		"category": "builtins",
		"title": "Delays"
	},
	"fb": {
		"keyword": "fb",
		"slug": "delays",
		"category": "builtins",
		"title": "Delays"
	},
	"effect": {
		"keyword": "effect",
		"slug": "delays",
		"category": "builtins",
		"title": "Delays"
	},
	"bp": {
		"keyword": "bp",
		"slug": "filters",
		"category": "builtins",
		"title": "bp",
		"anchor": "bp"
	},
	"bandpass": {
		"keyword": "bandpass",
		"slug": "filters",
		"category": "builtins",
		"title": "Filters"
	},
	"svf": {
		"keyword": "svf",
		"slug": "filters",
		"category": "builtins",
		"title": "Filters"
	},
	"q": {
		"keyword": "q",
		"slug": "filters",
		"category": "builtins",
		"title": "Filters"
	},
	"tanh": {
		"keyword": "tanh",
		"slug": "distortion",
		"category": "builtins",
		"title": "tanh",
		"anchor": "tanh"
	},
	"softclip": {
		"keyword": "softclip",
		"slug": "distortion",
		"category": "builtins",
		"title": "softclip",
		"anchor": "softclip"
	},
	"bitcrush": {
		"keyword": "bitcrush",
		"slug": "distortion",
		"category": "builtins",
		"title": "bitcrush",
		"anchor": "bitcrush"
	},
	"fold": {
		"keyword": "fold",
		"slug": "distortion",
		"category": "builtins",
		"title": "fold",
		"anchor": "fold"
	},
	"distortion": {
		"keyword": "distortion",
		"slug": "distortion",
		"category": "builtins",
		"title": "Distortion"
	},
	"wavefold": {
		"keyword": "wavefold",
		"slug": "distortion",
		"category": "builtins",
		"title": "Distortion"
	},
	"saturate": {
		"keyword": "saturate",
		"slug": "distortion",
		"category": "builtins",
		"title": "Distortion"
	},
	"drive": {
		"keyword": "drive",
		"slug": "distortion",
		"category": "builtins",
		"title": "Distortion"
	},
	"crush": {
		"keyword": "crush",
		"slug": "distortion",
		"category": "builtins",
		"title": "Distortion"
	},
	"lofi": {
		"keyword": "lofi",
		"slug": "distortion",
		"category": "builtins",
		"title": "Distortion"
	},
	"out": {
		"keyword": "out",
		"slug": "utility",
		"category": "builtins",
		"title": "out",
		"anchor": "out"
	},
	"mtof": {
		"keyword": "mtof",
		"slug": "utility",
		"category": "builtins",
		"title": "mtof",
		"anchor": "mtof"
	},
	"dc": {
		"keyword": "dc",
		"slug": "utility",
		"category": "builtins",
		"title": "dc",
		"anchor": "dc"
	},
	"slew": {
		"keyword": "slew",
		"slug": "utility",
		"category": "builtins",
		"title": "slew",
		"anchor": "slew"
	},
	"sah": {
		"keyword": "sah",
		"slug": "utility",
		"category": "builtins",
		"title": "sah",
		"anchor": "sah"
	},
	"utility": {
		"keyword": "utility",
		"slug": "utility",
		"category": "builtins",
		"title": "Utility"
	},
	"midi": {
		"keyword": "midi",
		"slug": "utility",
		"category": "builtins",
		"title": "Utility"
	},
	"frequency": {
		"keyword": "frequency",
		"slug": "utility",
		"category": "builtins",
		"title": "Utility"
	},
	"sample": {
		"keyword": "sample",
		"slug": "utility",
		"category": "builtins",
		"title": "Utility"
	},
	"hold": {
		"keyword": "hold",
		"slug": "utility",
		"category": "builtins",
		"title": "Utility"
	},
	"attack": {
		"keyword": "attack",
		"slug": "envelopes",
		"category": "builtins",
		"title": "Envelopes"
	},
	"decay": {
		"keyword": "decay",
		"slug": "envelopes",
		"category": "builtins",
		"title": "Envelopes"
	},
	"sustain": {
		"keyword": "sustain",
		"slug": "envelopes",
		"category": "builtins",
		"title": "Envelopes"
	},
	"release": {
		"keyword": "release",
		"slug": "envelopes",
		"category": "builtins",
		"title": "Envelopes"
	},
	"gate": {
		"keyword": "gate",
		"slug": "dynamics",
		"category": "builtins",
		"title": "gate",
		"anchor": "gate"
	},
	"chorus": {
		"keyword": "chorus",
		"slug": "modulation",
		"category": "builtins",
		"title": "chorus",
		"anchor": "chorus"
	},
	"flanger": {
		"keyword": "flanger",
		"slug": "modulation",
		"category": "builtins",
		"title": "flanger",
		"anchor": "flanger"
	},
	"phaser": {
		"keyword": "phaser",
		"slug": "modulation",
		"category": "builtins",
		"title": "phaser",
		"anchor": "phaser"
	},
	"comb": {
		"keyword": "comb",
		"slug": "modulation",
		"category": "builtins",
		"title": "comb",
		"anchor": "comb"
	},
	"modulation": {
		"keyword": "modulation",
		"slug": "modulation",
		"category": "builtins",
		"title": "Modulation Effects"
	},
	"rate": {
		"keyword": "rate",
		"slug": "modulation",
		"category": "builtins",
		"title": "Modulation Effects"
	},
	"depth": {
		"keyword": "depth",
		"slug": "modulation",
		"category": "builtins",
		"title": "Modulation Effects"
	},
	"sweep": {
		"keyword": "sweep",
		"slug": "modulation",
		"category": "builtins",
		"title": "Modulation Effects"
	},
	"unary math": {
		"keyword": "unary math",
		"slug": "math",
		"category": "builtins",
		"title": "Unary Math",
		"anchor": "unary-math"
	},
	"binary math": {
		"keyword": "binary math",
		"slug": "math",
		"category": "builtins",
		"title": "Binary Math",
		"anchor": "binary-math"
	},
	"ternary math": {
		"keyword": "ternary math",
		"slug": "math",
		"category": "builtins",
		"title": "Ternary Math",
		"anchor": "ternary-math"
	},
	"math": {
		"keyword": "math",
		"slug": "math",
		"category": "builtins",
		"title": "Math Functions"
	},
	"add": {
		"keyword": "add",
		"slug": "math",
		"category": "builtins",
		"title": "Math Functions"
	},
	"sub": {
		"keyword": "sub",
		"slug": "math",
		"category": "builtins",
		"title": "Math Functions"
	},
	"mul": {
		"keyword": "mul",
		"slug": "math",
		"category": "builtins",
		"title": "Math Functions"
	},
	"div": {
		"keyword": "div",
		"slug": "math",
		"category": "builtins",
		"title": "Math Functions"
	},
	"pow": {
		"keyword": "pow",
		"slug": "math",
		"category": "builtins",
		"title": "Math Functions"
	},
	"neg": {
		"keyword": "neg",
		"slug": "math",
		"category": "builtins",
		"title": "Math Functions"
	},
	"abs": {
		"keyword": "abs",
		"slug": "math",
		"category": "builtins",
		"title": "Math Functions"
	},
	"sqrt": {
		"keyword": "sqrt",
		"slug": "math",
		"category": "builtins",
		"title": "Math Functions"
	},
	"log": {
		"keyword": "log",
		"slug": "math",
		"category": "builtins",
		"title": "Math Functions"
	},
	"exp": {
		"keyword": "exp",
		"slug": "math",
		"category": "builtins",
		"title": "Math Functions"
	},
	"floor": {
		"keyword": "floor",
		"slug": "math",
		"category": "builtins",
		"title": "Math Functions"
	},
	"ceil": {
		"keyword": "ceil",
		"slug": "math",
		"category": "builtins",
		"title": "Math Functions"
	},
	"min": {
		"keyword": "min",
		"slug": "math",
		"category": "builtins",
		"title": "Math Functions"
	},
	"max": {
		"keyword": "max",
		"slug": "math",
		"category": "builtins",
		"title": "Math Functions"
	},
	"clamp": {
		"keyword": "clamp",
		"slug": "math",
		"category": "builtins",
		"title": "Math Functions"
	},
	"wrap": {
		"keyword": "wrap",
		"slug": "math",
		"category": "builtins",
		"title": "Math Functions"
	},
	"sin": {
		"keyword": "sin",
		"slug": "oscillators",
		"category": "builtins",
		"title": "sin",
		"anchor": "sin"
	},
	"tri": {
		"keyword": "tri",
		"slug": "oscillators",
		"category": "builtins",
		"title": "tri",
		"anchor": "tri"
	},
	"saw": {
		"keyword": "saw",
		"slug": "oscillators",
		"category": "builtins",
		"title": "saw",
		"anchor": "saw"
	},
	"sqr": {
		"keyword": "sqr",
		"slug": "oscillators",
		"category": "builtins",
		"title": "sqr",
		"anchor": "sqr"
	},
	"phasor": {
		"keyword": "phasor",
		"slug": "oscillators",
		"category": "builtins",
		"title": "phasor",
		"anchor": "phasor"
	},
	"ramp": {
		"keyword": "ramp",
		"slug": "oscillators",
		"category": "builtins",
		"title": "ramp",
		"anchor": "ramp"
	},
	"noise": {
		"keyword": "noise",
		"slug": "oscillators",
		"category": "builtins",
		"title": "noise",
		"anchor": "noise"
	},
	"triangle": {
		"keyword": "triangle",
		"slug": "oscillators",
		"category": "builtins",
		"title": "Oscillators"
	},
	"sawtooth": {
		"keyword": "sawtooth",
		"slug": "oscillators",
		"category": "builtins",
		"title": "Oscillators"
	},
	"square": {
		"keyword": "square",
		"slug": "oscillators",
		"category": "builtins",
		"title": "Oscillators"
	},
	"waveform": {
		"keyword": "waveform",
		"slug": "oscillators",
		"category": "builtins",
		"title": "Oscillators"
	},
	"tone": {
		"keyword": "tone",
		"slug": "oscillators",
		"category": "builtins",
		"title": "Oscillators"
	},
	"comp": {
		"keyword": "comp",
		"slug": "dynamics",
		"category": "builtins",
		"title": "comp",
		"anchor": "comp"
	},
	"limiter": {
		"keyword": "limiter",
		"slug": "dynamics",
		"category": "builtins",
		"title": "limiter",
		"anchor": "limiter"
	},
	"dynamics": {
		"keyword": "dynamics",
		"slug": "dynamics",
		"category": "builtins",
		"title": "Dynamics"
	},
	"compressor": {
		"keyword": "compressor",
		"slug": "dynamics",
		"category": "builtins",
		"title": "Dynamics"
	},
	"noisegate": {
		"keyword": "noisegate",
		"slug": "dynamics",
		"category": "builtins",
		"title": "Dynamics"
	},
	"threshold": {
		"keyword": "threshold",
		"slug": "dynamics",
		"category": "builtins",
		"title": "Dynamics"
	},
	"ratio": {
		"keyword": "ratio",
		"slug": "dynamics",
		"category": "builtins",
		"title": "Dynamics"
	},
	"ceiling": {
		"keyword": "ceiling",
		"slug": "dynamics",
		"category": "builtins",
		"title": "Dynamics"
	},
	"compression": {
		"keyword": "compression",
		"slug": "dynamics",
		"category": "builtins",
		"title": "Dynamics"
	},
	"freeverb": {
		"keyword": "freeverb",
		"slug": "reverbs",
		"category": "builtins",
		"title": "freeverb",
		"anchor": "freeverb"
	},
	"dattorro": {
		"keyword": "dattorro",
		"slug": "reverbs",
		"category": "builtins",
		"title": "dattorro",
		"anchor": "dattorro"
	},
	"fdn": {
		"keyword": "fdn",
		"slug": "reverbs",
		"category": "builtins",
		"title": "fdn",
		"anchor": "fdn"
	},
	"reverb": {
		"keyword": "reverb",
		"slug": "reverbs",
		"category": "builtins",
		"title": "Reverbs"
	},
	"room": {
		"keyword": "room",
		"slug": "reverbs",
		"category": "builtins",
		"title": "Reverbs"
	},
	"plate": {
		"keyword": "plate",
		"slug": "reverbs",
		"category": "builtins",
		"title": "Reverbs"
	},
	"space": {
		"keyword": "space",
		"slug": "reverbs",
		"category": "builtins",
		"title": "Reverbs"
	},
	"damping": {
		"keyword": "damping",
		"slug": "reverbs",
		"category": "builtins",
		"title": "Reverbs"
	},
	"wet": {
		"keyword": "wet",
		"slug": "reverbs",
		"category": "builtins",
		"title": "Reverbs"
	},
	"dry": {
		"keyword": "dry",
		"slug": "reverbs",
		"category": "builtins",
		"title": "Reverbs"
	},
	"contributing": {
		"keyword": "contributing",
		"slug": "DOCUMENTATION_GUIDE",
		"category": "concepts",
		"title": "Documentation Guide"
	},
	"documentation": {
		"keyword": "documentation",
		"slug": "DOCUMENTATION_GUIDE",
		"category": "concepts",
		"title": "Documentation Guide"
	},
	"guide": {
		"keyword": "guide",
		"slug": "DOCUMENTATION_GUIDE",
		"category": "concepts",
		"title": "Documentation Guide"
	},
	"standards": {
		"keyword": "standards",
		"slug": "DOCUMENTATION_GUIDE",
		"category": "concepts",
		"title": "Documentation Guide"
	}
};
