// Auto-generated by scripts/build-docs-index.ts
// Do not edit manually - run: bun run build:docs

export const slugToPath: Record<string, string> = {
	"03-synthesis": "tutorials/03-synthesis.md",
	"02-filters": "tutorials/02-filters.md",
	"04-rhythm": "tutorials/04-rhythm.md",
	"01-hello-sine": "tutorials/01-hello-sine.md",
	"basics": "reference/mini-notation/basics.md",
	"pipes": "reference/language/pipes.md",
	"variables": "reference/language/variables.md",
	"closures": "reference/language/closures.md",
	"operators": "reference/language/operators.md",
	"sequencing": "reference/builtins/sequencing.md",
	"delays": "reference/builtins/delays.md",
	"filters": "reference/builtins/filters.md",
	"distortion": "reference/builtins/distortion.md",
	"utility": "reference/builtins/utility.md",
	"envelopes": "reference/builtins/envelopes.md",
	"modulation": "reference/builtins/modulation.md",
	"math": "reference/builtins/math.md",
	"oscillators": "reference/builtins/oscillators.md",
	"dynamics": "reference/builtins/dynamics.md",
	"reverbs": "reference/builtins/reverbs.md",
	"DOCUMENTATION_GUIDE": "DOCUMENTATION_GUIDE.md"
};

export const navigation: Record<string, Array<{ slug: string; title: string }>> = {
	"tutorials": [
		{
			"slug": "01-hello-sine",
			"title": "Hello Sine"
		},
		{
			"slug": "02-filters",
			"title": "Shaping Sound with Filters"
		},
		{
			"slug": "03-synthesis",
			"title": "Building Synth Voices"
		},
		{
			"slug": "04-rhythm",
			"title": "Rhythm & Patterns"
		}
	],
	"builtins": [
		{
			"slug": "oscillators",
			"title": "Oscillators"
		},
		{
			"slug": "filters",
			"title": "Filters"
		},
		{
			"slug": "envelopes",
			"title": "Envelopes"
		},
		{
			"slug": "sequencing",
			"title": "Sequencing & Timing"
		},
		{
			"slug": "delays",
			"title": "Delays"
		},
		{
			"slug": "reverbs",
			"title": "Reverbs"
		},
		{
			"slug": "modulation",
			"title": "Modulation Effects"
		},
		{
			"slug": "distortion",
			"title": "Distortion"
		},
		{
			"slug": "dynamics",
			"title": "Dynamics"
		},
		{
			"slug": "math",
			"title": "Math Functions"
		},
		{
			"slug": "utility",
			"title": "Utility"
		}
	],
	"language": [
		{
			"slug": "pipes",
			"title": "Pipes & Holes"
		},
		{
			"slug": "variables",
			"title": "Variables & Assignment"
		},
		{
			"slug": "operators",
			"title": "Operators"
		},
		{
			"slug": "closures",
			"title": "Closures"
		}
	],
	"mini-notation": [
		{
			"slug": "basics",
			"title": "Mini-Notation Basics"
		}
	],
	"concepts": [
		{
			"slug": "DOCUMENTATION_GUIDE",
			"title": "Documentation Guide"
		}
	]
};

export const lookup: Record<string, { slug: string; category: string; title: string; anchor?: string }> = {
	"synthesis": {
		"slug": "03-synthesis",
		"category": "tutorials",
		"title": "Building Synth Voices"
	},
	"synth": {
		"slug": "03-synthesis",
		"category": "tutorials",
		"title": "Building Synth Voices"
	},
	"envelope": {
		"slug": "03-synthesis",
		"category": "tutorials",
		"title": "Building Synth Voices"
	},
	"adsr": {
		"slug": "envelopes",
		"category": "builtins",
		"title": "adsr",
		"anchor": "adsr"
	},
	"ar": {
		"slug": "envelopes",
		"category": "builtins",
		"title": "ar",
		"anchor": "ar"
	},
	"subtractive": {
		"slug": "03-synthesis",
		"category": "tutorials",
		"title": "Building Synth Voices"
	},
	"tutorial": {
		"slug": "03-synthesis",
		"category": "tutorials",
		"title": "Building Synth Voices"
	},
	"voice": {
		"slug": "03-synthesis",
		"category": "tutorials",
		"title": "Building Synth Voices"
	},
	"filter": {
		"slug": "02-filters",
		"category": "tutorials",
		"title": "Shaping Sound with Filters"
	},
	"lowpass": {
		"slug": "02-filters",
		"category": "tutorials",
		"title": "Shaping Sound with Filters"
	},
	"highpass": {
		"slug": "02-filters",
		"category": "tutorials",
		"title": "Shaping Sound with Filters"
	},
	"cutoff": {
		"slug": "02-filters",
		"category": "tutorials",
		"title": "Shaping Sound with Filters"
	},
	"resonance": {
		"slug": "02-filters",
		"category": "tutorials",
		"title": "Shaping Sound with Filters"
	},
	"lp": {
		"slug": "filters",
		"category": "builtins",
		"title": "lp",
		"anchor": "lp"
	},
	"hp": {
		"slug": "filters",
		"category": "builtins",
		"title": "hp",
		"anchor": "hp"
	},
	"moog": {
		"slug": "filters",
		"category": "builtins",
		"title": "moog",
		"anchor": "moog"
	},
	"rhythm": {
		"slug": "04-rhythm",
		"category": "tutorials",
		"title": "Rhythm & Patterns"
	},
	"pattern": {
		"slug": "04-rhythm",
		"category": "tutorials",
		"title": "Rhythm & Patterns"
	},
	"beat": {
		"slug": "04-rhythm",
		"category": "tutorials",
		"title": "Rhythm & Patterns"
	},
	"trigger": {
		"slug": "sequencing",
		"category": "builtins",
		"title": "trigger",
		"anchor": "trigger"
	},
	"euclidean": {
		"slug": "04-rhythm",
		"category": "tutorials",
		"title": "Rhythm & Patterns"
	},
	"sequencer": {
		"slug": "04-rhythm",
		"category": "tutorials",
		"title": "Rhythm & Patterns"
	},
	"clock": {
		"slug": "utility",
		"category": "builtins",
		"title": "clock",
		"anchor": "clock"
	},
	"getting started": {
		"slug": "01-hello-sine",
		"category": "tutorials",
		"title": "Hello Sine"
	},
	"first sound": {
		"slug": "01-hello-sine",
		"category": "tutorials",
		"title": "Hello Sine"
	},
	"sine": {
		"slug": "01-hello-sine",
		"category": "tutorials",
		"title": "Hello Sine"
	},
	"oscillator": {
		"slug": "01-hello-sine",
		"category": "tutorials",
		"title": "Hello Sine"
	},
	"output": {
		"slug": "01-hello-sine",
		"category": "tutorials",
		"title": "Hello Sine"
	},
	"beginner": {
		"slug": "01-hello-sine",
		"category": "tutorials",
		"title": "Hello Sine"
	},
	"mini-notation": {
		"slug": "basics",
		"category": "mini-notation",
		"title": "Mini-Notation Basics"
	},
	"sequence": {
		"slug": "basics",
		"category": "mini-notation",
		"title": "Mini-Notation Basics"
	},
	"pitch": {
		"slug": "basics",
		"category": "mini-notation",
		"title": "Mini-Notation Basics"
	},
	"chord": {
		"slug": "basics",
		"category": "mini-notation",
		"title": "Mini-Notation Basics"
	},
	"rest": {
		"slug": "basics",
		"category": "mini-notation",
		"title": "Mini-Notation Basics"
	},
	"tidal": {
		"slug": "basics",
		"category": "mini-notation",
		"title": "Mini-Notation Basics"
	},
	"strudel": {
		"slug": "basics",
		"category": "mini-notation",
		"title": "Mini-Notation Basics"
	},
	"pipe": {
		"slug": "pipes",
		"category": "language",
		"title": "Pipes & Holes"
	},
	"hole": {
		"slug": "pipes",
		"category": "language",
		"title": "Pipes & Holes"
	},
	"|>": {
		"slug": "pipes",
		"category": "language",
		"title": "Pipes & Holes"
	},
	"%": {
		"slug": "pipes",
		"category": "language",
		"title": "Pipes & Holes"
	},
	"signal flow": {
		"slug": "pipes",
		"category": "language",
		"title": "Pipes & Holes"
	},
	"graph": {
		"slug": "pipes",
		"category": "language",
		"title": "Pipes & Holes"
	},
	"connection": {
		"slug": "pipes",
		"category": "language",
		"title": "Pipes & Holes"
	},
	"routing": {
		"slug": "pipes",
		"category": "language",
		"title": "Pipes & Holes"
	},
	"variables": {
		"slug": "variables",
		"category": "language",
		"title": "Variables & Assignment"
	},
	"assignment": {
		"slug": "variables",
		"category": "language",
		"title": "Variables & Assignment"
	},
	"let": {
		"slug": "variables",
		"category": "language",
		"title": "Variables & Assignment"
	},
	"binding": {
		"slug": "variables",
		"category": "language",
		"title": "Variables & Assignment"
	},
	"scope": {
		"slug": "variables",
		"category": "language",
		"title": "Variables & Assignment"
	},
	"identifier": {
		"slug": "variables",
		"category": "language",
		"title": "Variables & Assignment"
	},
	"closures": {
		"slug": "closures",
		"category": "language",
		"title": "Closures"
	},
	"functions": {
		"slug": "closures",
		"category": "language",
		"title": "Closures"
	},
	"lambda": {
		"slug": "closures",
		"category": "language",
		"title": "Closures"
	},
	"anonymous": {
		"slug": "closures",
		"category": "language",
		"title": "Closures"
	},
	"arrow": {
		"slug": "closures",
		"category": "language",
		"title": "Closures"
	},
	"callback": {
		"slug": "closures",
		"category": "language",
		"title": "Closures"
	},
	"operators": {
		"slug": "operators",
		"category": "language",
		"title": "Operators"
	},
	"precedence": {
		"slug": "operators",
		"category": "language",
		"title": "Operators"
	},
	"arithmetic": {
		"slug": "math",
		"category": "builtins",
		"title": "Arithmetic",
		"anchor": "arithmetic"
	},
	"plus": {
		"slug": "operators",
		"category": "language",
		"title": "Operators"
	},
	"minus": {
		"slug": "operators",
		"category": "language",
		"title": "Operators"
	},
	"multiply": {
		"slug": "operators",
		"category": "language",
		"title": "Operators"
	},
	"divide": {
		"slug": "operators",
		"category": "language",
		"title": "Operators"
	},
	"power": {
		"slug": "operators",
		"category": "language",
		"title": "Operators"
	},
	"lfo": {
		"slug": "sequencing",
		"category": "builtins",
		"title": "lfo",
		"anchor": "lfo"
	},
	"euclid": {
		"slug": "sequencing",
		"category": "builtins",
		"title": "euclid",
		"anchor": "euclid"
	},
	"seq_step": {
		"slug": "sequencing",
		"category": "builtins",
		"title": "seq_step",
		"anchor": "seq-step"
	},
	"timeline": {
		"slug": "sequencing",
		"category": "builtins",
		"title": "timeline",
		"anchor": "timeline"
	},
	"sequencing": {
		"slug": "sequencing",
		"category": "builtins",
		"title": "Sequencing & Timing"
	},
	"timing": {
		"slug": "sequencing",
		"category": "builtins",
		"title": "Sequencing & Timing"
	},
	"delay": {
		"slug": "delays",
		"category": "builtins",
		"title": "delay",
		"anchor": "delay"
	},
	"echo": {
		"slug": "delays",
		"category": "builtins",
		"title": "Delays"
	},
	"feedback": {
		"slug": "delays",
		"category": "builtins",
		"title": "Delays"
	},
	"time": {
		"slug": "delays",
		"category": "builtins",
		"title": "Delays"
	},
	"fb": {
		"slug": "delays",
		"category": "builtins",
		"title": "Delays"
	},
	"effect": {
		"slug": "delays",
		"category": "builtins",
		"title": "Delays"
	},
	"bp": {
		"slug": "filters",
		"category": "builtins",
		"title": "bp",
		"anchor": "bp"
	},
	"bandpass": {
		"slug": "filters",
		"category": "builtins",
		"title": "Filters"
	},
	"svf": {
		"slug": "filters",
		"category": "builtins",
		"title": "Filters"
	},
	"q": {
		"slug": "filters",
		"category": "builtins",
		"title": "Filters"
	},
	"tanh": {
		"slug": "distortion",
		"category": "builtins",
		"title": "tanh",
		"anchor": "tanh"
	},
	"softclip": {
		"slug": "distortion",
		"category": "builtins",
		"title": "softclip",
		"anchor": "softclip"
	},
	"bitcrush": {
		"slug": "distortion",
		"category": "builtins",
		"title": "bitcrush",
		"anchor": "bitcrush"
	},
	"fold": {
		"slug": "distortion",
		"category": "builtins",
		"title": "fold",
		"anchor": "fold"
	},
	"tube": {
		"slug": "distortion",
		"category": "builtins",
		"title": "tube",
		"anchor": "tube"
	},
	"smooth": {
		"slug": "distortion",
		"category": "builtins",
		"title": "smooth",
		"anchor": "smooth"
	},
	"tape": {
		"slug": "distortion",
		"category": "builtins",
		"title": "tape",
		"anchor": "tape"
	},
	"xfmr": {
		"slug": "distortion",
		"category": "builtins",
		"title": "xfmr",
		"anchor": "xfmr"
	},
	"excite": {
		"slug": "distortion",
		"category": "builtins",
		"title": "excite",
		"anchor": "excite"
	},
	"distortion": {
		"slug": "distortion",
		"category": "builtins",
		"title": "Distortion"
	},
	"wavefold": {
		"slug": "distortion",
		"category": "builtins",
		"title": "Distortion"
	},
	"saturate": {
		"slug": "distortion",
		"category": "builtins",
		"title": "Distortion"
	},
	"drive": {
		"slug": "distortion",
		"category": "builtins",
		"title": "Distortion"
	},
	"crush": {
		"slug": "distortion",
		"category": "builtins",
		"title": "Distortion"
	},
	"lofi": {
		"slug": "distortion",
		"category": "builtins",
		"title": "Distortion"
	},
	"valve": {
		"slug": "distortion",
		"category": "builtins",
		"title": "Distortion"
	},
	"adaa": {
		"slug": "distortion",
		"category": "builtins",
		"title": "Distortion"
	},
	"warmth": {
		"slug": "distortion",
		"category": "builtins",
		"title": "Distortion"
	},
	"transformer": {
		"slug": "distortion",
		"category": "builtins",
		"title": "Distortion"
	},
	"exciter": {
		"slug": "distortion",
		"category": "builtins",
		"title": "Distortion"
	},
	"harmonics": {
		"slug": "distortion",
		"category": "builtins",
		"title": "Distortion"
	},
	"out": {
		"slug": "utility",
		"category": "builtins",
		"title": "out",
		"anchor": "out"
	},
	"mtof": {
		"slug": "utility",
		"category": "builtins",
		"title": "mtof",
		"anchor": "mtof"
	},
	"dc": {
		"slug": "utility",
		"category": "builtins",
		"title": "dc",
		"anchor": "dc"
	},
	"slew": {
		"slug": "utility",
		"category": "builtins",
		"title": "slew",
		"anchor": "slew"
	},
	"sah": {
		"slug": "utility",
		"category": "builtins",
		"title": "sah",
		"anchor": "sah"
	},
	"utility": {
		"slug": "utility",
		"category": "builtins",
		"title": "Utility"
	},
	"midi": {
		"slug": "utility",
		"category": "builtins",
		"title": "Utility"
	},
	"frequency": {
		"slug": "utility",
		"category": "builtins",
		"title": "Utility"
	},
	"sample": {
		"slug": "utility",
		"category": "builtins",
		"title": "Utility"
	},
	"hold": {
		"slug": "utility",
		"category": "builtins",
		"title": "Utility"
	},
	"attack": {
		"slug": "envelopes",
		"category": "builtins",
		"title": "Envelopes"
	},
	"decay": {
		"slug": "envelopes",
		"category": "builtins",
		"title": "Envelopes"
	},
	"sustain": {
		"slug": "envelopes",
		"category": "builtins",
		"title": "Envelopes"
	},
	"release": {
		"slug": "envelopes",
		"category": "builtins",
		"title": "Envelopes"
	},
	"gate": {
		"slug": "dynamics",
		"category": "builtins",
		"title": "gate",
		"anchor": "gate"
	},
	"chorus": {
		"slug": "modulation",
		"category": "builtins",
		"title": "chorus",
		"anchor": "chorus"
	},
	"flanger": {
		"slug": "modulation",
		"category": "builtins",
		"title": "flanger",
		"anchor": "flanger"
	},
	"phaser": {
		"slug": "modulation",
		"category": "builtins",
		"title": "phaser",
		"anchor": "phaser"
	},
	"comb": {
		"slug": "modulation",
		"category": "builtins",
		"title": "comb",
		"anchor": "comb"
	},
	"modulation": {
		"slug": "modulation",
		"category": "builtins",
		"title": "Modulation Effects"
	},
	"rate": {
		"slug": "modulation",
		"category": "builtins",
		"title": "Modulation Effects"
	},
	"depth": {
		"slug": "modulation",
		"category": "builtins",
		"title": "Modulation Effects"
	},
	"sweep": {
		"slug": "modulation",
		"category": "builtins",
		"title": "Modulation Effects"
	},
	"unary math": {
		"slug": "math",
		"category": "builtins",
		"title": "Unary Math",
		"anchor": "unary-math"
	},
	"binary math": {
		"slug": "math",
		"category": "builtins",
		"title": "Binary Math",
		"anchor": "binary-math"
	},
	"ternary math": {
		"slug": "math",
		"category": "builtins",
		"title": "Ternary Math",
		"anchor": "ternary-math"
	},
	"math": {
		"slug": "math",
		"category": "builtins",
		"title": "Math Functions"
	},
	"add": {
		"slug": "math",
		"category": "builtins",
		"title": "Math Functions"
	},
	"sub": {
		"slug": "math",
		"category": "builtins",
		"title": "Math Functions"
	},
	"mul": {
		"slug": "math",
		"category": "builtins",
		"title": "Math Functions"
	},
	"div": {
		"slug": "math",
		"category": "builtins",
		"title": "Math Functions"
	},
	"pow": {
		"slug": "math",
		"category": "builtins",
		"title": "Math Functions"
	},
	"neg": {
		"slug": "math",
		"category": "builtins",
		"title": "Math Functions"
	},
	"abs": {
		"slug": "math",
		"category": "builtins",
		"title": "Math Functions"
	},
	"sqrt": {
		"slug": "math",
		"category": "builtins",
		"title": "Math Functions"
	},
	"log": {
		"slug": "math",
		"category": "builtins",
		"title": "Math Functions"
	},
	"exp": {
		"slug": "math",
		"category": "builtins",
		"title": "Math Functions"
	},
	"floor": {
		"slug": "math",
		"category": "builtins",
		"title": "Math Functions"
	},
	"ceil": {
		"slug": "math",
		"category": "builtins",
		"title": "Math Functions"
	},
	"min": {
		"slug": "math",
		"category": "builtins",
		"title": "Math Functions"
	},
	"max": {
		"slug": "math",
		"category": "builtins",
		"title": "Math Functions"
	},
	"clamp": {
		"slug": "math",
		"category": "builtins",
		"title": "Math Functions"
	},
	"wrap": {
		"slug": "math",
		"category": "builtins",
		"title": "Math Functions"
	},
	"sin": {
		"slug": "oscillators",
		"category": "builtins",
		"title": "sin",
		"anchor": "sin"
	},
	"tri": {
		"slug": "oscillators",
		"category": "builtins",
		"title": "tri",
		"anchor": "tri"
	},
	"saw": {
		"slug": "oscillators",
		"category": "builtins",
		"title": "saw",
		"anchor": "saw"
	},
	"sqr": {
		"slug": "oscillators",
		"category": "builtins",
		"title": "sqr",
		"anchor": "sqr"
	},
	"phasor": {
		"slug": "oscillators",
		"category": "builtins",
		"title": "phasor",
		"anchor": "phasor"
	},
	"ramp": {
		"slug": "oscillators",
		"category": "builtins",
		"title": "ramp",
		"anchor": "ramp"
	},
	"noise": {
		"slug": "oscillators",
		"category": "builtins",
		"title": "noise",
		"anchor": "noise"
	},
	"triangle": {
		"slug": "oscillators",
		"category": "builtins",
		"title": "Oscillators"
	},
	"sawtooth": {
		"slug": "oscillators",
		"category": "builtins",
		"title": "Oscillators"
	},
	"square": {
		"slug": "oscillators",
		"category": "builtins",
		"title": "Oscillators"
	},
	"waveform": {
		"slug": "oscillators",
		"category": "builtins",
		"title": "Oscillators"
	},
	"tone": {
		"slug": "oscillators",
		"category": "builtins",
		"title": "Oscillators"
	},
	"comp": {
		"slug": "dynamics",
		"category": "builtins",
		"title": "comp",
		"anchor": "comp"
	},
	"limiter": {
		"slug": "dynamics",
		"category": "builtins",
		"title": "limiter",
		"anchor": "limiter"
	},
	"dynamics": {
		"slug": "dynamics",
		"category": "builtins",
		"title": "Dynamics"
	},
	"compressor": {
		"slug": "dynamics",
		"category": "builtins",
		"title": "Dynamics"
	},
	"noisegate": {
		"slug": "dynamics",
		"category": "builtins",
		"title": "Dynamics"
	},
	"threshold": {
		"slug": "dynamics",
		"category": "builtins",
		"title": "Dynamics"
	},
	"ratio": {
		"slug": "dynamics",
		"category": "builtins",
		"title": "Dynamics"
	},
	"ceiling": {
		"slug": "dynamics",
		"category": "builtins",
		"title": "Dynamics"
	},
	"compression": {
		"slug": "dynamics",
		"category": "builtins",
		"title": "Dynamics"
	},
	"freeverb": {
		"slug": "reverbs",
		"category": "builtins",
		"title": "freeverb",
		"anchor": "freeverb"
	},
	"dattorro": {
		"slug": "reverbs",
		"category": "builtins",
		"title": "dattorro",
		"anchor": "dattorro"
	},
	"fdn": {
		"slug": "reverbs",
		"category": "builtins",
		"title": "fdn",
		"anchor": "fdn"
	},
	"reverb": {
		"slug": "reverbs",
		"category": "builtins",
		"title": "Reverbs"
	},
	"room": {
		"slug": "reverbs",
		"category": "builtins",
		"title": "Reverbs"
	},
	"plate": {
		"slug": "reverbs",
		"category": "builtins",
		"title": "Reverbs"
	},
	"space": {
		"slug": "reverbs",
		"category": "builtins",
		"title": "Reverbs"
	},
	"damping": {
		"slug": "reverbs",
		"category": "builtins",
		"title": "Reverbs"
	},
	"wet": {
		"slug": "reverbs",
		"category": "builtins",
		"title": "Reverbs"
	},
	"dry": {
		"slug": "reverbs",
		"category": "builtins",
		"title": "Reverbs"
	},
	"contributing": {
		"slug": "DOCUMENTATION_GUIDE",
		"category": "concepts",
		"title": "Documentation Guide"
	},
	"documentation": {
		"slug": "DOCUMENTATION_GUIDE",
		"category": "concepts",
		"title": "Documentation Guide"
	},
	"guide": {
		"slug": "DOCUMENTATION_GUIDE",
		"category": "concepts",
		"title": "Documentation Guide"
	},
	"standards": {
		"slug": "DOCUMENTATION_GUIDE",
		"category": "concepts",
		"title": "Documentation Guide"
	}
};
