// Auto-generated by scripts/build-docs-index.ts
// Do not edit manually - run: bun run build:docs

export const slugToPath: Record<string, string> = {
	"runtime-controls": "concepts/runtime-controls.md",
	"record-as-options": "concepts/record-as-options.md",
	"effect-parameters": "concepts/effect-parameters.md",
	"glide-and-interpolation": "concepts/glide-and-interpolation.md",
	"signals": "concepts/signals.md",
	"05-testing-progression": "tutorials/05-testing-progression.md",
	"03-synthesis": "tutorials/03-synthesis.md",
	"06-pattern-modulation": "tutorials/06-pattern-modulation.md",
	"02-filters": "tutorials/02-filters.md",
	"07-midi": "tutorials/07-midi.md",
	"04-rhythm": "tutorials/04-rhythm.md",
	"01-hello-sine": "tutorials/01-hello-sine.md",
	"chords": "reference/mini-notation/chords.md",
	"microtonal": "reference/mini-notation/microtonal.md",
	"basics": "reference/mini-notation/basics.md",
	"curve-notation": "reference/mini-notation/curve-notation.md",
	"literals": "reference/pattern/literals.md",
	"uri-schemes": "reference/uri-schemes.md",
	"records": "reference/language/records.md",
	"methods": "reference/language/methods.md",
	"conditionals": "reference/language/conditionals.md",
	"pipes": "reference/language/pipes.md",
	"arrays": "reference/language/arrays.md",
	"variables": "reference/language/variables.md",
	"closures": "reference/language/closures.md",
	"operators": "reference/language/operators.md",
	"audio-input": "reference/builtins/audio-input.md",
	"stereo": "reference/builtins/stereo.md",
	"unison": "reference/builtins/unison.md",
	"sequencing": "reference/builtins/sequencing.md",
	"delays": "reference/builtins/delays.md",
	"samples-loading": "reference/builtins/samples-loading.md",
	"polyphony": "reference/builtins/polyphony.md",
	"filters": "reference/builtins/filters.md",
	"midi-cc": "reference/builtins/midi-cc.md",
	"distortion": "reference/builtins/distortion.md",
	"utility": "reference/builtins/utility.md",
	"envelopes": "reference/builtins/envelopes.md",
	"modulation": "reference/builtins/modulation.md",
	"pianoroll": "reference/builtins/pianoroll.md",
	"math": "reference/builtins/math.md",
	"samplers": "reference/builtins/samplers.md",
	"oscillators": "reference/builtins/oscillators.md",
	"state": "reference/builtins/state.md",
	"edge": "reference/builtins/edge.md",
	"dynamics": "reference/builtins/dynamics.md",
	"oscilloscope": "reference/builtins/oscilloscope.md",
	"soundfonts": "reference/builtins/soundfonts.md",
	"timelines": "reference/builtins/timelines.md",
	"waterfall": "reference/builtins/waterfall.md",
	"spectrum": "reference/builtins/spectrum.md",
	"waveform": "reference/builtins/waveform.md",
	"reverbs": "reference/builtins/reverbs.md",
	"fm-synthesis": "reference/builtins/fm-synthesis.md",
	"visualizations": "reference/builtins/visualizations.md",
	"midi": "reference/builtins/midi.md",
	"DOCUMENTATION_GUIDE": "DOCUMENTATION_GUIDE.md"
};

export const navigation: Record<string, Array<{ slug: string; title: string }>> = {
	"tutorials": [
		{
			"slug": "01-hello-sine",
			"title": "Hello Sine"
		},
		{
			"slug": "02-filters",
			"title": "Shaping Sound with Filters"
		},
		{
			"slug": "03-synthesis",
			"title": "Building Synth Voices"
		},
		{
			"slug": "04-rhythm",
			"title": "Rhythm & Patterns"
		},
		{
			"slug": "05-testing-progression",
			"title": "Testing Progression"
		},
		{
			"slug": "06-pattern-modulation",
			"title": "Pattern Modulation"
		},
		{
			"slug": "07-midi",
			"title": "MIDI Input"
		}
	],
	"builtins": [
		{
			"slug": "oscillators",
			"title": "Oscillators"
		},
		{
			"slug": "filters",
			"title": "Filters"
		},
		{
			"slug": "envelopes",
			"title": "Envelopes"
		},
		{
			"slug": "sequencing",
			"title": "Sequencing & Timing"
		},
		{
			"slug": "delays",
			"title": "Delays"
		},
		{
			"slug": "reverbs",
			"title": "Reverbs"
		},
		{
			"slug": "modulation",
			"title": "Modulation Effects"
		},
		{
			"slug": "distortion",
			"title": "Distortion"
		},
		{
			"slug": "dynamics",
			"title": "Dynamics"
		},
		{
			"slug": "math",
			"title": "Math Functions"
		},
		{
			"slug": "state",
			"title": "State Cells"
		},
		{
			"slug": "utility",
			"title": "Utility"
		},
		{
			"slug": "edge",
			"title": "Edge Primitives"
		},
		{
			"slug": "stereo",
			"title": "Stereo"
		},
		{
			"slug": "visualizations",
			"title": "Visualizations"
		},
		{
			"slug": "audio-input",
			"title": "Audio Input"
		},
		{
			"slug": "fm-synthesis",
			"title": "FM Synthesis"
		},
		{
			"slug": "midi",
			"title": "MIDI Input"
		},
		{
			"slug": "midi-cc",
			"title": "MIDI CC"
		},
		{
			"slug": "samplers",
			"title": "Samplers"
		},
		{
			"slug": "soundfonts",
			"title": "SoundFonts"
		},
		{
			"slug": "samples-loading",
			"title": "Samples Loading"
		},
		{
			"slug": "polyphony",
			"title": "Polyphony"
		},
		{
			"slug": "unison",
			"title": "Unison"
		},
		{
			"slug": "timelines",
			"title": "Timelines"
		},
		{
			"slug": "oscilloscope",
			"title": "Oscilloscope"
		},
		{
			"slug": "waveform",
			"title": "Waveform"
		},
		{
			"slug": "spectrum",
			"title": "Spectrum Analyzer"
		},
		{
			"slug": "waterfall",
			"title": "Waterfall"
		},
		{
			"slug": "pianoroll",
			"title": "Piano Roll"
		}
	],
	"language": [
		{
			"slug": "pipes",
			"title": "Pipes & Holes"
		},
		{
			"slug": "variables",
			"title": "Variables & Assignment"
		},
		{
			"slug": "operators",
			"title": "Operators"
		},
		{
			"slug": "closures",
			"title": "Closures"
		},
		{
			"slug": "conditionals",
			"title": "Conditionals & Logic"
		},
		{
			"slug": "records",
			"title": "Records"
		},
		{
			"slug": "arrays",
			"title": "Arrays"
		},
		{
			"slug": "methods",
			"title": "Method Calls (UFCS)"
		}
	],
	"mini-notation": [
		{
			"slug": "basics",
			"title": "Mini-Notation Basics"
		},
		{
			"slug": "microtonal",
			"title": "Microtonal Notation"
		},
		{
			"slug": "chords",
			"title": "Chords"
		}
	],
	"concepts": [
		{
			"slug": "DOCUMENTATION_GUIDE",
			"title": "Documentation Guide"
		},
		{
			"slug": "signals",
			"title": "Mono & Stereo Signals"
		},
		{
			"slug": "glide-and-interpolation",
			"title": "Glide & Interpolation"
		},
		{
			"slug": "record-as-options",
			"title": "Records as Builtin Options"
		},
		{
			"slug": "runtime-controls",
			"title": "Runtime Controls"
		},
		{
			"slug": "effect-parameters",
			"title": "Effect Parameters Convention"
		}
	]
};

export const lookup: Record<string, { slug: string; category: string; title: string; anchor?: string }> = {
	"0": {
		"slug": "chords",
		"category": "mini-notation",
		"title": "Chords"
	},
	"5": {
		"slug": "chords",
		"category": "mini-notation",
		"title": "Chords"
	},
	"6": {
		"slug": "chords",
		"category": "mini-notation",
		"title": "Chords"
	},
	"7": {
		"slug": "chords",
		"category": "mini-notation",
		"title": "Chords"
	},
	"9": {
		"slug": "chords",
		"category": "mini-notation",
		"title": "Chords"
	},
	"11": {
		"slug": "chords",
		"category": "mini-notation",
		"title": "Chords"
	},
	"13": {
		"slug": "chords",
		"category": "mini-notation",
		"title": "Chords"
	},
	"808": {
		"slug": "samplers",
		"category": "builtins",
		"title": "Samplers"
	},
	"909": {
		"slug": "samplers",
		"category": "builtins",
		"title": "Samplers"
	},
	"param": {
		"slug": "runtime-controls",
		"category": "concepts",
		"title": "Runtime Controls"
	},
	"slider": {
		"slug": "runtime-controls",
		"category": "concepts",
		"title": "Runtime Controls"
	},
	"button": {
		"slug": "runtime-controls",
		"category": "concepts",
		"title": "Runtime Controls"
	},
	"toggle": {
		"slug": "runtime-controls",
		"category": "concepts",
		"title": "Runtime Controls"
	},
	"dropdown": {
		"slug": "runtime-controls",
		"category": "concepts",
		"title": "Runtime Controls"
	},
	"ui": {
		"slug": "runtime-controls",
		"category": "concepts",
		"title": "Runtime Controls"
	},
	"interactive": {
		"slug": "runtime-controls",
		"category": "concepts",
		"title": "Runtime Controls"
	},
	"controls": {
		"slug": "runtime-controls",
		"category": "concepts",
		"title": "Runtime Controls"
	},
	"live": {
		"slug": "runtime-controls",
		"category": "concepts",
		"title": "Runtime Controls"
	},
	"performance": {
		"slug": "runtime-controls",
		"category": "concepts",
		"title": "Runtime Controls"
	},
	"knob": {
		"slug": "runtime-controls",
		"category": "concepts",
		"title": "Runtime Controls"
	},
	"options": {
		"slug": "record-as-options",
		"category": "concepts",
		"title": "Records as Builtin Options"
	},
	"record": {
		"slug": "record-as-options",
		"category": "concepts",
		"title": "Records as Builtin Options"
	},
	"builtin": {
		"slug": "record-as-options",
		"category": "concepts",
		"title": "Records as Builtin Options"
	},
	"convention": {
		"slug": "record-as-options",
		"category": "concepts",
		"title": "Records as Builtin Options"
	},
	"optionschema": {
		"slug": "record-as-options",
		"category": "concepts",
		"title": "Records as Builtin Options"
	},
	"params": {
		"slug": "record-as-options",
		"category": "concepts",
		"title": "Records as Builtin Options"
	},
	"configuration": {
		"slug": "record-as-options",
		"category": "concepts",
		"title": "Records as Builtin Options"
	},
	"viz": {
		"slug": "record-as-options",
		"category": "concepts",
		"title": "Records as Builtin Options"
	},
	"autocomplete": {
		"slug": "record-as-options",
		"category": "concepts",
		"title": "Records as Builtin Options"
	},
	"effect": {
		"slug": "effect-parameters",
		"category": "concepts",
		"title": "Effect Parameters Convention"
	},
	"dry": {
		"slug": "effect-parameters",
		"category": "concepts",
		"title": "Effect Parameters Convention"
	},
	"wet": {
		"slug": "effect-parameters",
		"category": "concepts",
		"title": "Effect Parameters Convention"
	},
	"mix": {
		"slug": "effect-parameters",
		"category": "concepts",
		"title": "Effect Parameters Convention"
	},
	"parallel": {
		"slug": "effect-parameters",
		"category": "concepts",
		"title": "Effect Parameters Convention"
	},
	"parameters": {
		"slug": "effect-parameters",
		"category": "concepts",
		"title": "Effect Parameters Convention"
	},
	"category": {
		"slug": "effect-parameters",
		"category": "concepts",
		"title": "Effect Parameters Convention"
	},
	"additive": {
		"slug": "effect-parameters",
		"category": "concepts",
		"title": "Effect Parameters Convention"
	},
	"transform": {
		"slug": "effect-parameters",
		"category": "concepts",
		"title": "Effect Parameters Convention"
	},
	"drywet": {
		"slug": "effect-parameters",
		"category": "concepts",
		"title": "Effect Parameters Convention"
	},
	"glide": {
		"slug": "utility",
		"category": "builtins",
		"title": "glide",
		"anchor": "glide"
	},
	"portamento": {
		"slug": "glide-and-interpolation",
		"category": "concepts",
		"title": "Glide & Interpolation"
	},
	"interp": {
		"slug": "utility",
		"category": "builtins",
		"title": "interp",
		"anchor": "interp"
	},
	"interpolation": {
		"slug": "glide-and-interpolation",
		"category": "concepts",
		"title": "Glide & Interpolation"
	},
	"slew": {
		"slug": "utility",
		"category": "builtins",
		"title": "slew",
		"anchor": "slew"
	},
	"ease": {
		"slug": "glide-and-interpolation",
		"category": "concepts",
		"title": "Glide & Interpolation"
	},
	"ease-in": {
		"slug": "glide-and-interpolation",
		"category": "concepts",
		"title": "Glide & Interpolation"
	},
	"ease-out": {
		"slug": "glide-and-interpolation",
		"category": "concepts",
		"title": "Glide & Interpolation"
	},
	"cosine": {
		"slug": "glide-and-interpolation",
		"category": "concepts",
		"title": "Glide & Interpolation"
	},
	"log": {
		"slug": "glide-and-interpolation",
		"category": "concepts",
		"title": "Glide & Interpolation"
	},
	"pitch": {
		"slug": "glide-and-interpolation",
		"category": "concepts",
		"title": "Glide & Interpolation"
	},
	"transition": {
		"slug": "glide-and-interpolation",
		"category": "concepts",
		"title": "Glide & Interpolation"
	},
	"time-based": {
		"slug": "glide-and-interpolation",
		"category": "concepts",
		"title": "Glide & Interpolation"
	},
	"mono": {
		"slug": "polyphony",
		"category": "builtins",
		"title": "mono",
		"anchor": "mono"
	},
	"stereo": {
		"slug": "stereo",
		"category": "builtins",
		"title": "stereo",
		"anchor": "stereo"
	},
	"channels": {
		"slug": "signals",
		"category": "concepts",
		"title": "Mono & Stereo Signals"
	},
	"stereo-native": {
		"slug": "signals",
		"category": "concepts",
		"title": "Mono & Stereo Signals"
	},
	"conversion": {
		"slug": "signals",
		"category": "concepts",
		"title": "Mono & Stereo Signals"
	},
	"downmix": {
		"slug": "signals",
		"category": "concepts",
		"title": "Mono & Stereo Signals"
	},
	"upmix": {
		"slug": "signals",
		"category": "concepts",
		"title": "Mono & Stereo Signals"
	},
	"signal types": {
		"slug": "signals",
		"category": "concepts",
		"title": "Mono & Stereo Signals"
	},
	"testing": {
		"slug": "05-testing-progression",
		"category": "tutorials",
		"title": "Testing Progression"
	},
	"patterns": {
		"slug": "05-testing-progression",
		"category": "tutorials",
		"title": "Testing Progression"
	},
	"synthesis": {
		"slug": "05-testing-progression",
		"category": "tutorials",
		"title": "Testing Progression"
	},
	"triggers": {
		"slug": "05-testing-progression",
		"category": "tutorials",
		"title": "Testing Progression"
	},
	"envelopes": {
		"slug": "05-testing-progression",
		"category": "tutorials",
		"title": "Testing Progression"
	},
	"samples": {
		"slug": "samples-loading",
		"category": "builtins",
		"title": "samples",
		"anchor": "samples"
	},
	"filters": {
		"slug": "05-testing-progression",
		"category": "tutorials",
		"title": "Testing Progression"
	},
	"moog": {
		"slug": "filters",
		"category": "builtins",
		"title": "moog",
		"anchor": "moog"
	},
	"diode": {
		"slug": "05-testing-progression",
		"category": "tutorials",
		"title": "Testing Progression"
	},
	"sallenkey": {
		"slug": "filters",
		"category": "builtins",
		"title": "sallenkey",
		"anchor": "sallenkey"
	},
	"formant": {
		"slug": "05-testing-progression",
		"category": "tutorials",
		"title": "Testing Progression"
	},
	"distortion": {
		"slug": "05-testing-progression",
		"category": "tutorials",
		"title": "Testing Progression"
	},
	"saturate": {
		"slug": "distortion",
		"category": "builtins",
		"title": "saturate",
		"anchor": "saturate"
	},
	"bitcrush": {
		"slug": "distortion",
		"category": "builtins",
		"title": "bitcrush",
		"anchor": "bitcrush"
	},
	"fold": {
		"slug": "distortion",
		"category": "builtins",
		"title": "fold",
		"anchor": "fold"
	},
	"tube": {
		"slug": "distortion",
		"category": "builtins",
		"title": "tube",
		"anchor": "tube"
	},
	"tape": {
		"slug": "distortion",
		"category": "builtins",
		"title": "tape",
		"anchor": "tape"
	},
	"xfmr": {
		"slug": "distortion",
		"category": "builtins",
		"title": "xfmr",
		"anchor": "xfmr"
	},
	"excite": {
		"slug": "distortion",
		"category": "builtins",
		"title": "excite",
		"anchor": "excite"
	},
	"chorus": {
		"slug": "modulation",
		"category": "builtins",
		"title": "chorus",
		"anchor": "chorus"
	},
	"flanger": {
		"slug": "modulation",
		"category": "builtins",
		"title": "flanger",
		"anchor": "flanger"
	},
	"phaser": {
		"slug": "modulation",
		"category": "builtins",
		"title": "phaser",
		"anchor": "phaser"
	},
	"comb": {
		"slug": "modulation",
		"category": "builtins",
		"title": "comb",
		"anchor": "comb"
	},
	"reverb": {
		"slug": "05-testing-progression",
		"category": "tutorials",
		"title": "Testing Progression"
	},
	"freeverb": {
		"slug": "reverbs",
		"category": "builtins",
		"title": "freeverb",
		"anchor": "freeverb"
	},
	"dattorro": {
		"slug": "reverbs",
		"category": "builtins",
		"title": "dattorro",
		"anchor": "dattorro"
	},
	"fdn": {
		"slug": "reverbs",
		"category": "builtins",
		"title": "fdn",
		"anchor": "fdn"
	},
	"delay": {
		"slug": "delays",
		"category": "builtins",
		"title": "delay",
		"anchor": "delay"
	},
	"comp": {
		"slug": "dynamics",
		"category": "builtins",
		"title": "comp",
		"anchor": "comp"
	},
	"limiter": {
		"slug": "dynamics",
		"category": "builtins",
		"title": "limiter",
		"anchor": "limiter"
	},
	"gate": {
		"slug": "dynamics",
		"category": "builtins",
		"title": "gate",
		"anchor": "gate"
	},
	"sah": {
		"slug": "edge",
		"category": "builtins",
		"title": "sah",
		"anchor": "sah"
	},
	"lfo": {
		"slug": "sequencing",
		"category": "builtins",
		"title": "lfo",
		"anchor": "lfo"
	},
	"env_follower": {
		"slug": "05-testing-progression",
		"category": "tutorials",
		"title": "Testing Progression"
	},
	"synth": {
		"slug": "03-synthesis",
		"category": "tutorials",
		"title": "Building Synth Voices"
	},
	"envelope": {
		"slug": "03-synthesis",
		"category": "tutorials",
		"title": "Building Synth Voices"
	},
	"adsr": {
		"slug": "envelopes",
		"category": "builtins",
		"title": "adsr",
		"anchor": "adsr"
	},
	"ar": {
		"slug": "envelopes",
		"category": "builtins",
		"title": "ar",
		"anchor": "ar"
	},
	"subtractive": {
		"slug": "03-synthesis",
		"category": "tutorials",
		"title": "Building Synth Voices"
	},
	"tutorial": {
		"slug": "03-synthesis",
		"category": "tutorials",
		"title": "Building Synth Voices"
	},
	"voice": {
		"slug": "soundfonts",
		"category": "builtins",
		"title": "voice",
		"anchor": "voice"
	},
	"pattern": {
		"slug": "06-pattern-modulation",
		"category": "tutorials",
		"title": "Pattern Modulation"
	},
	"modulation": {
		"slug": "06-pattern-modulation",
		"category": "tutorials",
		"title": "Pattern Modulation"
	},
	"value pattern": {
		"slug": "06-pattern-modulation",
		"category": "tutorials",
		"title": "Pattern Modulation"
	},
	"v\"…\"": {
		"slug": "06-pattern-modulation",
		"category": "tutorials",
		"title": "Pattern Modulation"
	},
	"bend": {
		"slug": "06-pattern-modulation",
		"category": "tutorials",
		"title": "Pattern Modulation"
	},
	"aftertouch": {
		"slug": "06-pattern-modulation",
		"category": "tutorials",
		"title": "Pattern Modulation"
	},
	"dur": {
		"slug": "06-pattern-modulation",
		"category": "tutorials",
		"title": "Pattern Modulation"
	},
	"custom property": {
		"slug": "06-pattern-modulation",
		"category": "tutorials",
		"title": "Pattern Modulation"
	},
	"cutoff": {
		"slug": "06-pattern-modulation",
		"category": "tutorials",
		"title": "Pattern Modulation"
	},
	"scalar": {
		"slug": "06-pattern-modulation",
		"category": "tutorials",
		"title": "Pattern Modulation"
	},
	"coerce": {
		"slug": "06-pattern-modulation",
		"category": "tutorials",
		"title": "Pattern Modulation"
	},
	"filter": {
		"slug": "02-filters",
		"category": "tutorials",
		"title": "Shaping Sound with Filters"
	},
	"lowpass": {
		"slug": "02-filters",
		"category": "tutorials",
		"title": "Shaping Sound with Filters"
	},
	"highpass": {
		"slug": "02-filters",
		"category": "tutorials",
		"title": "Shaping Sound with Filters"
	},
	"resonance": {
		"slug": "02-filters",
		"category": "tutorials",
		"title": "Shaping Sound with Filters"
	},
	"lp": {
		"slug": "filters",
		"category": "builtins",
		"title": "lp",
		"anchor": "lp"
	},
	"hp": {
		"slug": "filters",
		"category": "builtins",
		"title": "hp",
		"anchor": "hp"
	},
	"midi": {
		"slug": "midi",
		"category": "builtins",
		"title": "midi",
		"anchor": "midi"
	},
	"keyboard": {
		"slug": "07-midi",
		"category": "tutorials",
		"title": "MIDI Input"
	},
	"controller": {
		"slug": "07-midi",
		"category": "tutorials",
		"title": "MIDI Input"
	},
	"cc": {
		"slug": "07-midi",
		"category": "tutorials",
		"title": "MIDI Input"
	},
	"pitch-bend": {
		"slug": "07-midi",
		"category": "tutorials",
		"title": "MIDI Input"
	},
	"soundfont": {
		"slug": "soundfonts",
		"category": "builtins",
		"title": "soundfont",
		"anchor": "soundfont"
	},
	".mid": {
		"slug": "07-midi",
		"category": "tutorials",
		"title": "MIDI Input"
	},
	"file": {
		"slug": "samples-loading",
		"category": "builtins",
		"title": "file",
		"anchor": "file"
	},
	"poly": {
		"slug": "polyphony",
		"category": "builtins",
		"title": "poly",
		"anchor": "poly"
	},
	"lead": {
		"slug": "07-midi",
		"category": "tutorials",
		"title": "MIDI Input"
	},
	"rhythm": {
		"slug": "04-rhythm",
		"category": "tutorials",
		"title": "Rhythm & Patterns"
	},
	"beat": {
		"slug": "04-rhythm",
		"category": "tutorials",
		"title": "Rhythm & Patterns"
	},
	"trigger": {
		"slug": "sequencing",
		"category": "builtins",
		"title": "trigger",
		"anchor": "trigger"
	},
	"euclidean": {
		"slug": "04-rhythm",
		"category": "tutorials",
		"title": "Rhythm & Patterns"
	},
	"sequencer": {
		"slug": "04-rhythm",
		"category": "tutorials",
		"title": "Rhythm & Patterns"
	},
	"clock": {
		"slug": "timelines",
		"category": "builtins",
		"title": "clock",
		"anchor": "clock"
	},
	"select": {
		"slug": "conditionals",
		"category": "language",
		"title": "select",
		"anchor": "select"
	},
	"conditional": {
		"slug": "04-rhythm",
		"category": "tutorials",
		"title": "Rhythm & Patterns"
	},
	"threshold": {
		"slug": "04-rhythm",
		"category": "tutorials",
		"title": "Rhythm & Patterns"
	},
	"and": {
		"slug": "04-rhythm",
		"category": "tutorials",
		"title": "Rhythm & Patterns"
	},
	"or": {
		"slug": "04-rhythm",
		"category": "tutorials",
		"title": "Rhythm & Patterns"
	},
	"not": {
		"slug": "04-rhythm",
		"category": "tutorials",
		"title": "Rhythm & Patterns"
	},
	"getting started": {
		"slug": "01-hello-sine",
		"category": "tutorials",
		"title": "Hello Sine"
	},
	"first sound": {
		"slug": "01-hello-sine",
		"category": "tutorials",
		"title": "Hello Sine"
	},
	"sine": {
		"slug": "01-hello-sine",
		"category": "tutorials",
		"title": "Hello Sine"
	},
	"oscillator": {
		"slug": "01-hello-sine",
		"category": "tutorials",
		"title": "Hello Sine"
	},
	"output": {
		"slug": "01-hello-sine",
		"category": "tutorials",
		"title": "Hello Sine"
	},
	"beginner": {
		"slug": "01-hello-sine",
		"category": "tutorials",
		"title": "Hello Sine"
	},
	"osc": {
		"slug": "oscillators",
		"category": "builtins",
		"title": "osc",
		"anchor": "osc"
	},
	"chord": {
		"slug": "chords",
		"category": "mini-notation",
		"title": "Chords"
	},
	"chords": {
		"slug": "chords",
		"category": "mini-notation",
		"title": "Chords"
	},
	"voicing": {
		"slug": "chords",
		"category": "mini-notation",
		"title": "Chords"
	},
	"voicings": {
		"slug": "chords",
		"category": "mini-notation",
		"title": "Chords"
	},
	"anchor": {
		"slug": "chords",
		"category": "mini-notation",
		"title": "Chords"
	},
	"mode": {
		"slug": "chords",
		"category": "mini-notation",
		"title": "Chords"
	},
	"addvoicings": {
		"slug": "chords",
		"category": "mini-notation",
		"title": "Chords"
	},
	"drop2": {
		"slug": "chords",
		"category": "mini-notation",
		"title": "Chords"
	},
	"drop3": {
		"slug": "chords",
		"category": "mini-notation",
		"title": "Chords"
	},
	"close": {
		"slug": "chords",
		"category": "mini-notation",
		"title": "Chords"
	},
	"open": {
		"slug": "chords",
		"category": "mini-notation",
		"title": "Chords"
	},
	"inversion": {
		"slug": "chords",
		"category": "mini-notation",
		"title": "Chords"
	},
	"triad": {
		"slug": "chords",
		"category": "mini-notation",
		"title": "Chords"
	},
	"seventh": {
		"slug": "chords",
		"category": "mini-notation",
		"title": "Chords"
	},
	"sixth": {
		"slug": "chords",
		"category": "mini-notation",
		"title": "Chords"
	},
	"ninth": {
		"slug": "chords",
		"category": "mini-notation",
		"title": "Chords"
	},
	"eleventh": {
		"slug": "chords",
		"category": "mini-notation",
		"title": "Chords"
	},
	"thirteenth": {
		"slug": "chords",
		"category": "mini-notation",
		"title": "Chords"
	},
	"extended": {
		"slug": "chords",
		"category": "mini-notation",
		"title": "Chords"
	},
	"polyphony": {
		"slug": "chords",
		"category": "mini-notation",
		"title": "Chords"
	},
	"e410": {
		"slug": "chords",
		"category": "mini-notation",
		"title": "Chords"
	},
	"m": {
		"slug": "chords",
		"category": "mini-notation",
		"title": "Chords"
	},
	"maj": {
		"slug": "chords",
		"category": "mini-notation",
		"title": "Chords"
	},
	"min": {
		"slug": "chords",
		"category": "mini-notation",
		"title": "Chords"
	},
	"dim": {
		"slug": "chords",
		"category": "mini-notation",
		"title": "Chords"
	},
	"aug": {
		"slug": "chords",
		"category": "mini-notation",
		"title": "Chords"
	},
	"sus": {
		"slug": "chords",
		"category": "mini-notation",
		"title": "Chords"
	},
	"sus2": {
		"slug": "chords",
		"category": "mini-notation",
		"title": "Chords"
	},
	"sus4": {
		"slug": "chords",
		"category": "mini-notation",
		"title": "Chords"
	},
	"power": {
		"slug": "chords",
		"category": "mini-notation",
		"title": "Chords"
	},
	"m6": {
		"slug": "chords",
		"category": "mini-notation",
		"title": "Chords"
	},
	"min6": {
		"slug": "chords",
		"category": "mini-notation",
		"title": "Chords"
	},
	"dom7": {
		"slug": "chords",
		"category": "mini-notation",
		"title": "Chords"
	},
	"m7": {
		"slug": "chords",
		"category": "mini-notation",
		"title": "Chords"
	},
	"maj7": {
		"slug": "chords",
		"category": "mini-notation",
		"title": "Chords"
	},
	"^": {
		"slug": "chords",
		"category": "mini-notation",
		"title": "Chords"
	},
	"^7": {
		"slug": "chords",
		"category": "mini-notation",
		"title": "Chords"
	},
	"min7": {
		"slug": "chords",
		"category": "mini-notation",
		"title": "Chords"
	},
	"-7": {
		"slug": "chords",
		"category": "mini-notation",
		"title": "Chords"
	},
	"dim7": {
		"slug": "chords",
		"category": "mini-notation",
		"title": "Chords"
	},
	"o7": {
		"slug": "chords",
		"category": "mini-notation",
		"title": "Chords"
	},
	"m7b5": {
		"slug": "chords",
		"category": "mini-notation",
		"title": "Chords"
	},
	"aug7": {
		"slug": "chords",
		"category": "mini-notation",
		"title": "Chords"
	},
	"+7": {
		"slug": "chords",
		"category": "mini-notation",
		"title": "Chords"
	},
	"mm7": {
		"slug": "chords",
		"category": "mini-notation",
		"title": "Chords"
	},
	"m^7": {
		"slug": "chords",
		"category": "mini-notation",
		"title": "Chords"
	},
	"minmaj7": {
		"slug": "chords",
		"category": "mini-notation",
		"title": "Chords"
	},
	"m9": {
		"slug": "chords",
		"category": "mini-notation",
		"title": "Chords"
	},
	"maj9": {
		"slug": "chords",
		"category": "mini-notation",
		"title": "Chords"
	},
	"min9": {
		"slug": "chords",
		"category": "mini-notation",
		"title": "Chords"
	},
	"add9": {
		"slug": "chords",
		"category": "mini-notation",
		"title": "Chords"
	},
	"add2": {
		"slug": "chords",
		"category": "mini-notation",
		"title": "Chords"
	},
	"m11": {
		"slug": "chords",
		"category": "mini-notation",
		"title": "Chords"
	},
	"-": {
		"slug": "chords",
		"category": "mini-notation",
		"title": "Chords"
	},
	"+": {
		"slug": "chords",
		"category": "mini-notation",
		"title": "Chords"
	},
	"o": {
		"slug": "chords",
		"category": "mini-notation",
		"title": "Chords"
	},
	"microtonal": {
		"slug": "microtonal",
		"category": "mini-notation",
		"title": "Microtonal Notation"
	},
	"tuning": {
		"slug": "microtonal",
		"category": "mini-notation",
		"title": "Microtonal Notation"
	},
	"edo": {
		"slug": "microtonal",
		"category": "mini-notation",
		"title": "Microtonal Notation"
	},
	"quarter tone": {
		"slug": "microtonal",
		"category": "mini-notation",
		"title": "Microtonal Notation"
	},
	"17edo": {
		"slug": "microtonal",
		"category": "mini-notation",
		"title": "Microtonal Notation"
	},
	"24edo": {
		"slug": "microtonal",
		"category": "mini-notation",
		"title": "Microtonal Notation"
	},
	"31edo": {
		"slug": "microtonal",
		"category": "mini-notation",
		"title": "Microtonal Notation"
	},
	"tune": {
		"slug": "microtonal",
		"category": "mini-notation",
		"title": "Microtonal Notation"
	},
	"xenharmonic": {
		"slug": "microtonal",
		"category": "mini-notation",
		"title": "Microtonal Notation"
	},
	"cents": {
		"slug": "microtonal",
		"category": "mini-notation",
		"title": "Microtonal Notation"
	},
	"micro-step": {
		"slug": "microtonal",
		"category": "mini-notation",
		"title": "Microtonal Notation"
	},
	"step up": {
		"slug": "microtonal",
		"category": "mini-notation",
		"title": "Microtonal Notation"
	},
	"step down": {
		"slug": "microtonal",
		"category": "mini-notation",
		"title": "Microtonal Notation"
	},
	"caret": {
		"slug": "microtonal",
		"category": "mini-notation",
		"title": "Microtonal Notation"
	},
	"mini-notation": {
		"slug": "basics",
		"category": "mini-notation",
		"title": "Mini-Notation Basics"
	},
	"sequence": {
		"slug": "basics",
		"category": "mini-notation",
		"title": "Mini-Notation Basics"
	},
	"rest": {
		"slug": "basics",
		"category": "mini-notation",
		"title": "Mini-Notation Basics"
	},
	"tidal": {
		"slug": "basics",
		"category": "mini-notation",
		"title": "Mini-Notation Basics"
	},
	"strudel": {
		"slug": "basics",
		"category": "mini-notation",
		"title": "Mini-Notation Basics"
	},
	"modifier": {
		"slug": "basics",
		"category": "mini-notation",
		"title": "Mini-Notation Basics"
	},
	"speed": {
		"slug": "waterfall",
		"category": "builtins",
		"title": "speed",
		"anchor": "speed"
	},
	"slow": {
		"slug": "basics",
		"category": "mini-notation",
		"title": "Mini-Notation Basics"
	},
	"repeat": {
		"slug": "arrays",
		"category": "language",
		"title": "repeat",
		"anchor": "repeat"
	},
	"chance": {
		"slug": "basics",
		"category": "mini-notation",
		"title": "Mini-Notation Basics"
	},
	"alternation": {
		"slug": "basics",
		"category": "mini-notation",
		"title": "Mini-Notation Basics"
	},
	"curve": {
		"slug": "timelines",
		"category": "builtins",
		"title": "curve",
		"anchor": "curve"
	},
	"timeline": {
		"slug": "timelines",
		"category": "builtins",
		"title": "timeline",
		"anchor": "timeline"
	},
	"automation": {
		"slug": "timelines",
		"category": "builtins",
		"title": "automation",
		"anchor": "automation"
	},
	"t\"": {
		"slug": "curve-notation",
		"category": "reference",
		"title": "Curve Notation"
	},
	"breakpoint": {
		"slug": "timelines",
		"category": "builtins",
		"title": "breakpoint",
		"anchor": "breakpoint"
	},
	"literal": {
		"slug": "literals",
		"category": "pattern",
		"title": "Pattern Literals"
	},
	"prefix": {
		"slug": "literals",
		"category": "pattern",
		"title": "Pattern Literals"
	},
	"value": {
		"slug": "literals",
		"category": "pattern",
		"title": "Pattern Literals"
	},
	"note": {
		"slug": "literals",
		"category": "pattern",
		"title": "Pattern Literals"
	},
	"sample": {
		"slug": "samplers",
		"category": "builtins",
		"title": "sample",
		"anchor": "sample"
	},
	"n\"…\"": {
		"slug": "literals",
		"category": "pattern",
		"title": "Pattern Literals"
	},
	"s\"…\"": {
		"slug": "literals",
		"category": "pattern",
		"title": "Pattern Literals"
	},
	"c\"…\"": {
		"slug": "literals",
		"category": "pattern",
		"title": "Pattern Literals"
	},
	"p\"…\"": {
		"slug": "literals",
		"category": "pattern",
		"title": "Pattern Literals"
	},
	"typed prefix": {
		"slug": "literals",
		"category": "pattern",
		"title": "Pattern Literals"
	},
	"uri": {
		"slug": "uri-schemes",
		"category": "reference",
		"title": "URI Schemes"
	},
	"resolver": {
		"slug": "uri-schemes",
		"category": "reference",
		"title": "URI Schemes"
	},
	"wavetable": {
		"slug": "uri-schemes",
		"category": "reference",
		"title": "URI Schemes"
	},
	"github": {
		"slug": "samples-loading",
		"category": "builtins",
		"title": "github",
		"anchor": "github"
	},
	"http": {
		"slug": "samples-loading",
		"category": "builtins",
		"title": "http",
		"anchor": "http"
	},
	"https": {
		"slug": "uri-schemes",
		"category": "reference",
		"title": "URI Schemes"
	},
	"bundled": {
		"slug": "uri-schemes",
		"category": "reference",
		"title": "URI Schemes"
	},
	"blob": {
		"slug": "uri-schemes",
		"category": "reference",
		"title": "URI Schemes"
	},
	"idb": {
		"slug": "uri-schemes",
		"category": "reference",
		"title": "URI Schemes"
	},
	"asset loading": {
		"slug": "uri-schemes",
		"category": "reference",
		"title": "URI Schemes"
	},
	"smf": {
		"slug": "uri-schemes",
		"category": "reference",
		"title": "URI Schemes"
	},
	"field": {
		"slug": "records",
		"category": "language",
		"title": "Records"
	},
	"dot": {
		"slug": "records",
		"category": "language",
		"title": "Records"
	},
	"access": {
		"slug": "records",
		"category": "language",
		"title": "Records"
	},
	"destructure": {
		"slug": "records",
		"category": "language",
		"title": "Records"
	},
	"spread": {
		"slug": "polyphony",
		"category": "builtins",
		"title": "spread",
		"anchor": "spread"
	},
	"state": {
		"slug": "state",
		"category": "builtins",
		"title": "state",
		"anchor": "state"
	},
	"struct": {
		"slug": "records",
		"category": "language",
		"title": "Records"
	},
	"named-fields": {
		"slug": "records",
		"category": "language",
		"title": "Records"
	},
	"pattern-event": {
		"slug": "records",
		"category": "language",
		"title": "Records"
	},
	"method": {
		"slug": "methods",
		"category": "language",
		"title": "Method Calls (UFCS)"
	},
	"ufcs": {
		"slug": "methods",
		"category": "language",
		"title": "Method Calls (UFCS)"
	},
	"call": {
		"slug": "methods",
		"category": "language",
		"title": "Method Calls (UFCS)"
	},
	"syntax": {
		"slug": "methods",
		"category": "language",
		"title": "Method Calls (UFCS)"
	},
	"chain": {
		"slug": "methods",
		"category": "language",
		"title": "Method Calls (UFCS)"
	},
	"truth convention": {
		"slug": "conditionals",
		"category": "language",
		"title": "Truth convention",
		"anchor": "truth-convention"
	},
	"gt": {
		"slug": "conditionals",
		"category": "language",
		"title": "gt",
		"anchor": "gt"
	},
	"lt": {
		"slug": "conditionals",
		"category": "language",
		"title": "lt",
		"anchor": "lt"
	},
	"gte": {
		"slug": "conditionals",
		"category": "language",
		"title": "gte",
		"anchor": "gte"
	},
	"lte": {
		"slug": "conditionals",
		"category": "language",
		"title": "lte",
		"anchor": "lte"
	},
	"eq": {
		"slug": "conditionals",
		"category": "language",
		"title": "eq",
		"anchor": "eq"
	},
	"neq": {
		"slug": "conditionals",
		"category": "language",
		"title": "neq",
		"anchor": "neq"
	},
	"band": {
		"slug": "conditionals",
		"category": "language",
		"title": "band",
		"anchor": "band"
	},
	"bor": {
		"slug": "conditionals",
		"category": "language",
		"title": "bor",
		"anchor": "bor"
	},
	"bnot": {
		"slug": "conditionals",
		"category": "language",
		"title": "bnot",
		"anchor": "bnot"
	},
	"see also": {
		"slug": "conditionals",
		"category": "language",
		"title": "See also",
		"anchor": "see-also"
	},
	"conditionals": {
		"slug": "conditionals",
		"category": "language",
		"title": "Conditionals & Logic"
	},
	"logic": {
		"slug": "conditionals",
		"category": "language",
		"title": "Conditionals & Logic"
	},
	"comparison": {
		"slug": "conditionals",
		"category": "language",
		"title": "Conditionals & Logic"
	},
	"ternary": {
		"slug": "conditionals",
		"category": "language",
		"title": "Conditionals & Logic"
	},
	"if": {
		"slug": "conditionals",
		"category": "language",
		"title": "Conditionals & Logic"
	},
	"else": {
		"slug": "conditionals",
		"category": "language",
		"title": "Conditionals & Logic"
	},
	"boolean": {
		"slug": "conditionals",
		"category": "language",
		"title": "Conditionals & Logic"
	},
	"equal": {
		"slug": "conditionals",
		"category": "language",
		"title": "Conditionals & Logic"
	},
	"equality": {
		"slug": "conditionals",
		"category": "language",
		"title": "Conditionals & Logic"
	},
	"greater": {
		"slug": "conditionals",
		"category": "language",
		"title": "Conditionals & Logic"
	},
	"less": {
		"slug": "conditionals",
		"category": "language",
		"title": "Conditionals & Logic"
	},
	"pipe": {
		"slug": "pipes",
		"category": "language",
		"title": "Pipes & Holes"
	},
	"hole": {
		"slug": "pipes",
		"category": "language",
		"title": "Pipes & Holes"
	},
	"|>": {
		"slug": "pipes",
		"category": "language",
		"title": "Pipes & Holes"
	},
	"@": {
		"slug": "pipes",
		"category": "language",
		"title": "Pipes & Holes"
	},
	"signal flow": {
		"slug": "pipes",
		"category": "language",
		"title": "Pipes & Holes"
	},
	"graph": {
		"slug": "pipes",
		"category": "language",
		"title": "Pipes & Holes"
	},
	"connection": {
		"slug": "pipes",
		"category": "language",
		"title": "Pipes & Holes"
	},
	"routing": {
		"slug": "pipes",
		"category": "language",
		"title": "Pipes & Holes"
	},
	"array literals": {
		"slug": "arrays",
		"category": "language",
		"title": "Array literals",
		"anchor": "array-literals"
	},
	"indexing": {
		"slug": "arrays",
		"category": "language",
		"title": "Indexing",
		"anchor": "indexing"
	},
	"auto-expansion via map and sum": {
		"slug": "arrays",
		"category": "language",
		"title": "Auto-expansion via map and sum",
		"anchor": "auto-expansion-via-map-and-sum"
	},
	"len": {
		"slug": "arrays",
		"category": "language",
		"title": "len",
		"anchor": "len"
	},
	"map": {
		"slug": "arrays",
		"category": "language",
		"title": "map",
		"anchor": "map"
	},
	"reduce": {
		"slug": "arrays",
		"category": "language",
		"title": "reduce",
		"anchor": "reduce"
	},
	"zipwith": {
		"slug": "arrays",
		"category": "language",
		"title": "zipWith",
		"anchor": "zipwith"
	},
	"zip": {
		"slug": "arrays",
		"category": "language",
		"title": "zip",
		"anchor": "zip"
	},
	"take": {
		"slug": "arrays",
		"category": "language",
		"title": "take",
		"anchor": "take"
	},
	"drop": {
		"slug": "arrays",
		"category": "language",
		"title": "drop",
		"anchor": "drop"
	},
	"reverse": {
		"slug": "arrays",
		"category": "language",
		"title": "reverse",
		"anchor": "reverse"
	},
	"sum": {
		"slug": "arrays",
		"category": "language",
		"title": "sum",
		"anchor": "sum"
	},
	"mean": {
		"slug": "arrays",
		"category": "language",
		"title": "mean",
		"anchor": "mean"
	},
	"rotate": {
		"slug": "arrays",
		"category": "language",
		"title": "rotate",
		"anchor": "rotate"
	},
	"shuffle": {
		"slug": "arrays",
		"category": "language",
		"title": "shuffle",
		"anchor": "shuffle"
	},
	"sort": {
		"slug": "arrays",
		"category": "language",
		"title": "sort",
		"anchor": "sort"
	},
	"normalize": {
		"slug": "arrays",
		"category": "language",
		"title": "normalize",
		"anchor": "normalize"
	},
	"scale": {
		"slug": "waveform",
		"category": "builtins",
		"title": "scale",
		"anchor": "scale"
	},
	"range": {
		"slug": "arrays",
		"category": "language",
		"title": "range",
		"anchor": "range"
	},
	"linspace": {
		"slug": "arrays",
		"category": "language",
		"title": "linspace",
		"anchor": "linspace"
	},
	"random": {
		"slug": "arrays",
		"category": "language",
		"title": "random",
		"anchor": "random"
	},
	"harmonics": {
		"slug": "arrays",
		"category": "language",
		"title": "harmonics",
		"anchor": "harmonics"
	},
	"polyphony builtins": {
		"slug": "arrays",
		"category": "language",
		"title": "Polyphony builtins",
		"anchor": "polyphony-builtins"
	},
	"common patterns": {
		"slug": "arrays",
		"category": "language",
		"title": "Common patterns",
		"anchor": "common-patterns"
	},
	"array": {
		"slug": "arrays",
		"category": "language",
		"title": "Arrays"
	},
	"list": {
		"slug": "arrays",
		"category": "language",
		"title": "Arrays"
	},
	"arrays": {
		"slug": "arrays",
		"category": "language",
		"title": "Arrays"
	},
	"length": {
		"slug": "arrays",
		"category": "language",
		"title": "Arrays"
	},
	"average": {
		"slug": "arrays",
		"category": "language",
		"title": "Arrays"
	},
	"voices": {
		"slug": "polyphony",
		"category": "builtins",
		"title": "voices",
		"anchor": "voices"
	},
	"multi-buffer": {
		"slug": "arrays",
		"category": "language",
		"title": "Arrays"
	},
	"comprehension": {
		"slug": "arrays",
		"category": "language",
		"title": "Arrays"
	},
	"index": {
		"slug": "fm-synthesis",
		"category": "builtins",
		"title": "index",
		"anchor": "index"
	},
	"variadic": {
		"slug": "arrays",
		"category": "language",
		"title": "Arrays"
	},
	"variables": {
		"slug": "variables",
		"category": "language",
		"title": "Variables & Assignment"
	},
	"assignment": {
		"slug": "variables",
		"category": "language",
		"title": "Variables & Assignment"
	},
	"let": {
		"slug": "variables",
		"category": "language",
		"title": "Variables & Assignment"
	},
	"binding": {
		"slug": "variables",
		"category": "language",
		"title": "Variables & Assignment"
	},
	"scope": {
		"slug": "variables",
		"category": "language",
		"title": "Variables & Assignment"
	},
	"identifier": {
		"slug": "variables",
		"category": "language",
		"title": "Variables & Assignment"
	},
	"closures": {
		"slug": "closures",
		"category": "language",
		"title": "Closures"
	},
	"functions": {
		"slug": "closures",
		"category": "language",
		"title": "Closures"
	},
	"lambda": {
		"slug": "closures",
		"category": "language",
		"title": "Closures"
	},
	"anonymous": {
		"slug": "closures",
		"category": "language",
		"title": "Closures"
	},
	"arrow": {
		"slug": "closures",
		"category": "language",
		"title": "Closures"
	},
	"callback": {
		"slug": "closures",
		"category": "language",
		"title": "Closures"
	},
	"partial": {
		"slug": "closures",
		"category": "language",
		"title": "Closures"
	},
	"compose": {
		"slug": "closures",
		"category": "language",
		"title": "Closures"
	},
	"factory": {
		"slug": "closures",
		"category": "language",
		"title": "Closures"
	},
	"underscore": {
		"slug": "closures",
		"category": "language",
		"title": "Closures"
	},
	"placeholder": {
		"slug": "closures",
		"category": "language",
		"title": "Closures"
	},
	"operators": {
		"slug": "operators",
		"category": "language",
		"title": "Operators"
	},
	"precedence": {
		"slug": "operators",
		"category": "language",
		"title": "Operators"
	},
	"arithmetic": {
		"slug": "math",
		"category": "builtins",
		"title": "Arithmetic",
		"anchor": "arithmetic"
	},
	"plus": {
		"slug": "operators",
		"category": "language",
		"title": "Operators"
	},
	"minus": {
		"slug": "operators",
		"category": "language",
		"title": "Operators"
	},
	"multiply": {
		"slug": "operators",
		"category": "language",
		"title": "Operators"
	},
	"divide": {
		"slug": "operators",
		"category": "language",
		"title": "Operators"
	},
	"in": {
		"slug": "audio-input",
		"category": "builtins",
		"title": "in",
		"anchor": "in"
	},
	"input": {
		"slug": "audio-input",
		"category": "builtins",
		"title": "Audio Input"
	},
	"microphone": {
		"slug": "audio-input",
		"category": "builtins",
		"title": "Audio Input"
	},
	"mic": {
		"slug": "audio-input",
		"category": "builtins",
		"title": "Audio Input"
	},
	"tab": {
		"slug": "audio-input",
		"category": "builtins",
		"title": "Audio Input"
	},
	"audio": {
		"slug": "audio-input",
		"category": "builtins",
		"title": "Audio Input"
	},
	"capture": {
		"slug": "audio-input",
		"category": "builtins",
		"title": "Audio Input"
	},
	"getusermedia": {
		"slug": "audio-input",
		"category": "builtins",
		"title": "Audio Input"
	},
	"left, right": {
		"slug": "stereo",
		"category": "builtins",
		"title": "left, right",
		"anchor": "left-right"
	},
	"pan": {
		"slug": "stereo",
		"category": "builtins",
		"title": "pan",
		"anchor": "pan"
	},
	"width": {
		"slug": "stereo",
		"category": "builtins",
		"title": "width",
		"anchor": "width"
	},
	"ms_encode, ms_decode": {
		"slug": "stereo",
		"category": "builtins",
		"title": "ms_encode, ms_decode",
		"anchor": "ms-encode-ms-decode"
	},
	"pingpong": {
		"slug": "stereo",
		"category": "builtins",
		"title": "pingpong",
		"anchor": "pingpong"
	},
	"stereo-native effects": {
		"slug": "stereo",
		"category": "builtins",
		"title": "Stereo-native effects",
		"anchor": "stereo-native-effects"
	},
	"left": {
		"slug": "stereo",
		"category": "builtins",
		"title": "Stereo"
	},
	"right": {
		"slug": "stereo",
		"category": "builtins",
		"title": "Stereo"
	},
	"ms_encode": {
		"slug": "stereo",
		"category": "builtins",
		"title": "Stereo"
	},
	"ms_decode": {
		"slug": "stereo",
		"category": "builtins",
		"title": "Stereo"
	},
	"unison": {
		"slug": "unison",
		"category": "builtins",
		"title": "unison",
		"anchor": "unison"
	},
	"supersaw": {
		"slug": "unison",
		"category": "builtins",
		"title": "Unison"
	},
	"fatten": {
		"slug": "unison",
		"category": "builtins",
		"title": "Unison"
	},
	"fat": {
		"slug": "unison",
		"category": "builtins",
		"title": "Unison"
	},
	"detune": {
		"slug": "unison",
		"category": "builtins",
		"title": "Unison"
	},
	"phase": {
		"slug": "unison",
		"category": "builtins",
		"title": "Unison"
	},
	"stack": {
		"slug": "unison",
		"category": "builtins",
		"title": "Unison"
	},
	"cluster": {
		"slug": "unison",
		"category": "builtins",
		"title": "Unison"
	},
	"euclid": {
		"slug": "sequencing",
		"category": "builtins",
		"title": "euclid",
		"anchor": "euclid"
	},
	"pattern transforms": {
		"slug": "sequencing",
		"category": "builtins",
		"title": "Pattern transforms",
		"anchor": "pattern-transforms"
	},
	"pattern generators": {
		"slug": "sequencing",
		"category": "builtins",
		"title": "Pattern generators",
		"anchor": "pattern-generators"
	},
	"sequencing": {
		"slug": "sequencing",
		"category": "builtins",
		"title": "Sequencing & Timing"
	},
	"timing": {
		"slug": "sequencing",
		"category": "builtins",
		"title": "Sequencing & Timing"
	},
	"early": {
		"slug": "sequencing",
		"category": "builtins",
		"title": "Sequencing & Timing"
	},
	"late": {
		"slug": "sequencing",
		"category": "builtins",
		"title": "Sequencing & Timing"
	},
	"palindrome": {
		"slug": "sequencing",
		"category": "builtins",
		"title": "Sequencing & Timing"
	},
	"compress": {
		"slug": "sequencing",
		"category": "builtins",
		"title": "Sequencing & Timing"
	},
	"ply": {
		"slug": "sequencing",
		"category": "builtins",
		"title": "Sequencing & Timing"
	},
	"linger": {
		"slug": "sequencing",
		"category": "builtins",
		"title": "Sequencing & Timing"
	},
	"zoom": {
		"slug": "sequencing",
		"category": "builtins",
		"title": "Sequencing & Timing"
	},
	"segment": {
		"slug": "sequencing",
		"category": "builtins",
		"title": "Sequencing & Timing"
	},
	"swing": {
		"slug": "sequencing",
		"category": "builtins",
		"title": "Sequencing & Timing"
	},
	"swingby": {
		"slug": "sequencing",
		"category": "builtins",
		"title": "Sequencing & Timing"
	},
	"iter": {
		"slug": "sequencing",
		"category": "builtins",
		"title": "Sequencing & Timing"
	},
	"iterback": {
		"slug": "sequencing",
		"category": "builtins",
		"title": "Sequencing & Timing"
	},
	"run": {
		"slug": "sequencing",
		"category": "builtins",
		"title": "Sequencing & Timing"
	},
	"binary": {
		"slug": "sequencing",
		"category": "builtins",
		"title": "Sequencing & Timing"
	},
	"binaryn": {
		"slug": "sequencing",
		"category": "builtins",
		"title": "Sequencing & Timing"
	},
	"delay_ms": {
		"slug": "delays",
		"category": "builtins",
		"title": "delay_ms",
		"anchor": "delay-ms"
	},
	"delay_smp": {
		"slug": "delays",
		"category": "builtins",
		"title": "delay_smp",
		"anchor": "delay-smp"
	},
	"tap_delay": {
		"slug": "delays",
		"category": "builtins",
		"title": "tap_delay",
		"anchor": "tap-delay"
	},
	"tap_delay_ms": {
		"slug": "delays",
		"category": "builtins",
		"title": "tap_delay_ms",
		"anchor": "tap-delay-ms"
	},
	"tap_delay_smp": {
		"slug": "delays",
		"category": "builtins",
		"title": "tap_delay_smp",
		"anchor": "tap-delay-smp"
	},
	"echo": {
		"slug": "delays",
		"category": "builtins",
		"title": "Delays"
	},
	"feedback": {
		"slug": "delays",
		"category": "builtins",
		"title": "Delays"
	},
	"time": {
		"slug": "delays",
		"category": "builtins",
		"title": "Delays"
	},
	"fb": {
		"slug": "delays",
		"category": "builtins",
		"title": "Delays"
	},
	"bank": {
		"slug": "samples-loading",
		"category": "builtins",
		"title": "bank",
		"anchor": "bank"
	},
	"url": {
		"slug": "samples-loading",
		"category": "builtins",
		"title": "url",
		"anchor": "url"
	},
	"drag-drop": {
		"slug": "samples-loading",
		"category": "builtins",
		"title": "drag-drop",
		"anchor": "drag-drop"
	},
	"asset": {
		"slug": "samples-loading",
		"category": "builtins",
		"title": "asset",
		"anchor": "asset"
	},
	"loading": {
		"slug": "samples-loading",
		"category": "builtins",
		"title": "Samples Loading"
	},
	"registry": {
		"slug": "samples-loading",
		"category": "builtins",
		"title": "Samples Loading"
	},
	"samples-directive": {
		"slug": "samples-loading",
		"category": "builtins",
		"title": "Samples Loading"
	},
	"dirt-samples": {
		"slug": "samples-loading",
		"category": "builtins",
		"title": "Samples Loading"
	},
	"legato": {
		"slug": "polyphony",
		"category": "builtins",
		"title": "legato",
		"anchor": "legato"
	},
	"polyphonic": {
		"slug": "soundfonts",
		"category": "builtins",
		"title": "polyphonic",
		"anchor": "polyphonic"
	},
	"instrument": {
		"slug": "soundfonts",
		"category": "builtins",
		"title": "instrument",
		"anchor": "instrument"
	},
	"allocation": {
		"slug": "polyphony",
		"category": "builtins",
		"title": "Polyphony"
	},
	"retrigger": {
		"slug": "polyphony",
		"category": "builtins",
		"title": "Polyphony"
	},
	"voice-stealing": {
		"slug": "polyphony",
		"category": "builtins",
		"title": "Polyphony"
	},
	"release": {
		"slug": "polyphony",
		"category": "builtins",
		"title": "Polyphony"
	},
	"release-window": {
		"slug": "polyphony",
		"category": "builtins",
		"title": "Polyphony"
	},
	"note-off": {
		"slug": "polyphony",
		"category": "builtins",
		"title": "Polyphony"
	},
	"click": {
		"slug": "polyphony",
		"category": "builtins",
		"title": "Polyphony"
	},
	"bp": {
		"slug": "filters",
		"category": "builtins",
		"title": "bp",
		"anchor": "bp"
	},
	"bandpass": {
		"slug": "filters",
		"category": "builtins",
		"title": "Filters"
	},
	"svf": {
		"slug": "filters",
		"category": "builtins",
		"title": "Filters"
	},
	"q": {
		"slug": "filters",
		"category": "builtins",
		"title": "Filters"
	},
	"midi_cc": {
		"slug": "midi-cc",
		"category": "builtins",
		"title": "midi_cc",
		"anchor": "midi-cc"
	},
	"control-change": {
		"slug": "midi-cc",
		"category": "builtins",
		"title": "MIDI CC"
	},
	"control change": {
		"slug": "midi-cc",
		"category": "builtins",
		"title": "MIDI CC"
	},
	"pitchbend": {
		"slug": "midi-cc",
		"category": "builtins",
		"title": "MIDI CC"
	},
	"pb": {
		"slug": "midi-cc",
		"category": "builtins",
		"title": "MIDI CC"
	},
	"channel-pressure": {
		"slug": "midi-cc",
		"category": "builtins",
		"title": "MIDI CC"
	},
	"at": {
		"slug": "midi-cc",
		"category": "builtins",
		"title": "MIDI CC"
	},
	"route": {
		"slug": "midi-cc",
		"category": "builtins",
		"title": "MIDI CC"
	},
	"envmap": {
		"slug": "midi-cc",
		"category": "builtins",
		"title": "MIDI CC"
	},
	"channel": {
		"slug": "midi-cc",
		"category": "builtins",
		"title": "MIDI CC"
	},
	"modwheel": {
		"slug": "midi-cc",
		"category": "builtins",
		"title": "MIDI CC"
	},
	"softclip": {
		"slug": "distortion",
		"category": "builtins",
		"title": "softclip",
		"anchor": "softclip"
	},
	"smooth": {
		"slug": "distortion",
		"category": "builtins",
		"title": "smooth",
		"anchor": "smooth"
	},
	"wavefold": {
		"slug": "distortion",
		"category": "builtins",
		"title": "Distortion"
	},
	"drive": {
		"slug": "distortion",
		"category": "builtins",
		"title": "Distortion"
	},
	"crush": {
		"slug": "distortion",
		"category": "builtins",
		"title": "Distortion"
	},
	"lofi": {
		"slug": "distortion",
		"category": "builtins",
		"title": "Distortion"
	},
	"valve": {
		"slug": "distortion",
		"category": "builtins",
		"title": "Distortion"
	},
	"adaa": {
		"slug": "distortion",
		"category": "builtins",
		"title": "Distortion"
	},
	"warmth": {
		"slug": "distortion",
		"category": "builtins",
		"title": "Distortion"
	},
	"transformer": {
		"slug": "distortion",
		"category": "builtins",
		"title": "Distortion"
	},
	"exciter": {
		"slug": "distortion",
		"category": "builtins",
		"title": "Distortion"
	},
	"out": {
		"slug": "utility",
		"category": "builtins",
		"title": "out",
		"anchor": "out"
	},
	"mtof": {
		"slug": "utility",
		"category": "builtins",
		"title": "mtof",
		"anchor": "mtof"
	},
	"dc": {
		"slug": "utility",
		"category": "builtins",
		"title": "dc",
		"anchor": "dc"
	},
	"interp_ease_in": {
		"slug": "utility",
		"category": "builtins",
		"title": "interp_ease_in",
		"anchor": "interp-ease-in"
	},
	"interp_ease_out": {
		"slug": "utility",
		"category": "builtins",
		"title": "interp_ease_out",
		"anchor": "interp-ease-out"
	},
	"interp_cos": {
		"slug": "utility",
		"category": "builtins",
		"title": "interp_cos",
		"anchor": "interp-cos"
	},
	"utility": {
		"slug": "utility",
		"category": "builtins",
		"title": "Utility"
	},
	"frequency": {
		"slug": "utility",
		"category": "builtins",
		"title": "Utility"
	},
	"hold": {
		"slug": "utility",
		"category": "builtins",
		"title": "Utility"
	},
	"attack": {
		"slug": "envelopes",
		"category": "builtins",
		"title": "Envelopes"
	},
	"decay": {
		"slug": "envelopes",
		"category": "builtins",
		"title": "Envelopes"
	},
	"sustain": {
		"slug": "envelopes",
		"category": "builtins",
		"title": "Envelopes"
	},
	"rate": {
		"slug": "modulation",
		"category": "builtins",
		"title": "Modulation Effects"
	},
	"depth": {
		"slug": "modulation",
		"category": "builtins",
		"title": "Modulation Effects"
	},
	"sweep": {
		"slug": "modulation",
		"category": "builtins",
		"title": "Modulation Effects"
	},
	"lfo_phase": {
		"slug": "modulation",
		"category": "builtins",
		"title": "Modulation Effects"
	},
	"decorrelation": {
		"slug": "modulation",
		"category": "builtins",
		"title": "Modulation Effects"
	},
	"extended-params": {
		"slug": "modulation",
		"category": "builtins",
		"title": "Modulation Effects"
	},
	"pianoroll": {
		"slug": "visualizations",
		"category": "builtins",
		"title": "pianoroll",
		"anchor": "pianoroll"
	},
	"beats": {
		"slug": "pianoroll",
		"category": "builtins",
		"title": "beats",
		"anchor": "beats"
	},
	"showgrid": {
		"slug": "pianoroll",
		"category": "builtins",
		"title": "showGrid",
		"anchor": "showgrid"
	},
	"chromatic": {
		"slug": "pianoroll",
		"category": "builtins",
		"title": "chromatic",
		"anchor": "chromatic"
	},
	"pentatonic": {
		"slug": "pianoroll",
		"category": "builtins",
		"title": "pentatonic",
		"anchor": "pentatonic"
	},
	"octave": {
		"slug": "pianoroll",
		"category": "builtins",
		"title": "octave",
		"anchor": "octave"
	},
	"piano": {
		"slug": "pianoroll",
		"category": "builtins",
		"title": "Piano Roll"
	},
	"roll": {
		"slug": "pianoroll",
		"category": "builtins",
		"title": "Piano Roll"
	},
	"visualization": {
		"slug": "pianoroll",
		"category": "builtins",
		"title": "Piano Roll"
	},
	"events": {
		"slug": "pianoroll",
		"category": "builtins",
		"title": "Piano Roll"
	},
	"grid": {
		"slug": "pianoroll",
		"category": "builtins",
		"title": "Piano Roll"
	},
	"unary math": {
		"slug": "math",
		"category": "builtins",
		"title": "Unary math",
		"anchor": "unary-math"
	},
	"binary math": {
		"slug": "math",
		"category": "builtins",
		"title": "Binary math",
		"anchor": "binary-math"
	},
	"ternary math": {
		"slug": "math",
		"category": "builtins",
		"title": "Ternary math",
		"anchor": "ternary-math"
	},
	"trigonometric functions": {
		"slug": "math",
		"category": "builtins",
		"title": "Trigonometric functions",
		"anchor": "trigonometric-functions"
	},
	"hyperbolic functions": {
		"slug": "math",
		"category": "builtins",
		"title": "Hyperbolic functions",
		"anchor": "hyperbolic-functions"
	},
	"math": {
		"slug": "math",
		"category": "builtins",
		"title": "Math Functions"
	},
	"add": {
		"slug": "math",
		"category": "builtins",
		"title": "Math Functions"
	},
	"sub": {
		"slug": "math",
		"category": "builtins",
		"title": "Math Functions"
	},
	"mul": {
		"slug": "math",
		"category": "builtins",
		"title": "Math Functions"
	},
	"div": {
		"slug": "math",
		"category": "builtins",
		"title": "Math Functions"
	},
	"pow": {
		"slug": "math",
		"category": "builtins",
		"title": "Math Functions"
	},
	"neg": {
		"slug": "math",
		"category": "builtins",
		"title": "Math Functions"
	},
	"abs": {
		"slug": "math",
		"category": "builtins",
		"title": "Math Functions"
	},
	"sqrt": {
		"slug": "math",
		"category": "builtins",
		"title": "Math Functions"
	},
	"exp": {
		"slug": "math",
		"category": "builtins",
		"title": "Math Functions"
	},
	"floor": {
		"slug": "math",
		"category": "builtins",
		"title": "Math Functions"
	},
	"ceil": {
		"slug": "math",
		"category": "builtins",
		"title": "Math Functions"
	},
	"max": {
		"slug": "math",
		"category": "builtins",
		"title": "Math Functions"
	},
	"clamp": {
		"slug": "math",
		"category": "builtins",
		"title": "Math Functions"
	},
	"wrap": {
		"slug": "math",
		"category": "builtins",
		"title": "Math Functions"
	},
	"sin": {
		"slug": "math",
		"category": "builtins",
		"title": "Math Functions"
	},
	"cos": {
		"slug": "math",
		"category": "builtins",
		"title": "Math Functions"
	},
	"tan": {
		"slug": "math",
		"category": "builtins",
		"title": "Math Functions"
	},
	"asin": {
		"slug": "math",
		"category": "builtins",
		"title": "Math Functions"
	},
	"acos": {
		"slug": "math",
		"category": "builtins",
		"title": "Math Functions"
	},
	"atan": {
		"slug": "math",
		"category": "builtins",
		"title": "Math Functions"
	},
	"atan2": {
		"slug": "math",
		"category": "builtins",
		"title": "Math Functions"
	},
	"sinh": {
		"slug": "math",
		"category": "builtins",
		"title": "Math Functions"
	},
	"cosh": {
		"slug": "math",
		"category": "builtins",
		"title": "Math Functions"
	},
	"tanh": {
		"slug": "math",
		"category": "builtins",
		"title": "Math Functions"
	},
	"trigonometry": {
		"slug": "math",
		"category": "builtins",
		"title": "Math Functions"
	},
	"hyperbolic": {
		"slug": "math",
		"category": "builtins",
		"title": "Math Functions"
	},
	"sample_loop": {
		"slug": "samplers",
		"category": "builtins",
		"title": "sample_loop",
		"anchor": "sample-loop"
	},
	"bd": {
		"slug": "samplers",
		"category": "builtins",
		"title": "bd",
		"anchor": "bd"
	},
	"sd": {
		"slug": "samplers",
		"category": "builtins",
		"title": "sd",
		"anchor": "sd"
	},
	"hh": {
		"slug": "samplers",
		"category": "builtins",
		"title": "hh",
		"anchor": "hh"
	},
	"oh": {
		"slug": "samplers",
		"category": "builtins",
		"title": "oh",
		"anchor": "oh"
	},
	"cp": {
		"slug": "samplers",
		"category": "builtins",
		"title": "cp",
		"anchor": "cp"
	},
	"sampler": {
		"slug": "samplers",
		"category": "builtins",
		"title": "Samplers"
	},
	"drum": {
		"slug": "samplers",
		"category": "builtins",
		"title": "Samplers"
	},
	"kit": {
		"slug": "samplers",
		"category": "builtins",
		"title": "Samplers"
	},
	"percussion": {
		"slug": "samplers",
		"category": "builtins",
		"title": "Samplers"
	},
	"playback": {
		"slug": "samplers",
		"category": "builtins",
		"title": "Samplers"
	},
	"one-shot": {
		"slug": "samplers",
		"category": "builtins",
		"title": "Samplers"
	},
	"loop": {
		"slug": "samplers",
		"category": "builtins",
		"title": "Samplers"
	},
	"tri": {
		"slug": "oscillators",
		"category": "builtins",
		"title": "Oscillators"
	},
	"triangle": {
		"slug": "oscillators",
		"category": "builtins",
		"title": "Oscillators"
	},
	"saw": {
		"slug": "oscillators",
		"category": "builtins",
		"title": "Oscillators"
	},
	"sawtooth": {
		"slug": "oscillators",
		"category": "builtins",
		"title": "Oscillators"
	},
	"sqr": {
		"slug": "oscillators",
		"category": "builtins",
		"title": "Oscillators"
	},
	"square": {
		"slug": "oscillators",
		"category": "builtins",
		"title": "Oscillators"
	},
	"phasor": {
		"slug": "oscillators",
		"category": "builtins",
		"title": "Oscillators"
	},
	"ramp": {
		"slug": "oscillators",
		"category": "builtins",
		"title": "Oscillators"
	},
	"noise": {
		"slug": "oscillators",
		"category": "builtins",
		"title": "Oscillators"
	},
	"waveform": {
		"slug": "visualizations",
		"category": "builtins",
		"title": "waveform",
		"anchor": "waveform"
	},
	"tone": {
		"slug": "oscillators",
		"category": "builtins",
		"title": "Oscillators"
	},
	"get": {
		"slug": "state",
		"category": "builtins",
		"title": "get",
		"anchor": "get"
	},
	"set": {
		"slug": "state",
		"category": "builtins",
		"title": "set",
		"anchor": "set"
	},
	"example: writing a stepper in userspace": {
		"slug": "state",
		"category": "builtins",
		"title": "Example: writing a stepper in userspace",
		"anchor": "example-writing-a-stepper-in-userspace"
	},
	"record-valued state cells": {
		"slug": "state",
		"category": "builtins",
		"title": "Record-valued state cells",
		"anchor": "record-valued-state-cells"
	},
	"cell": {
		"slug": "state",
		"category": "builtins",
		"title": "State Cells"
	},
	"persistent": {
		"slug": "state",
		"category": "builtins",
		"title": "State Cells"
	},
	"register": {
		"slug": "state",
		"category": "builtins",
		"title": "State Cells"
	},
	"slot": {
		"slug": "state",
		"category": "builtins",
		"title": "State Cells"
	},
	"memory": {
		"slug": "state",
		"category": "builtins",
		"title": "State Cells"
	},
	"counter": {
		"slug": "edge",
		"category": "builtins",
		"title": "counter",
		"anchor": "counter"
	},
	"accumulator": {
		"slug": "state",
		"category": "builtins",
		"title": "State Cells"
	},
	"store": {
		"slug": "state",
		"category": "builtins",
		"title": "State Cells"
	},
	"gateup": {
		"slug": "edge",
		"category": "builtins",
		"title": "gateup",
		"anchor": "gateup"
	},
	"gatedown": {
		"slug": "edge",
		"category": "builtins",
		"title": "gatedown",
		"anchor": "gatedown"
	},
	"edge": {
		"slug": "edge",
		"category": "builtins",
		"title": "Edge Primitives"
	},
	"rising": {
		"slug": "oscilloscope",
		"category": "builtins",
		"title": "rising",
		"anchor": "rising"
	},
	"falling": {
		"slug": "oscilloscope",
		"category": "builtins",
		"title": "falling",
		"anchor": "falling"
	},
	"sample-and-hold": {
		"slug": "edge",
		"category": "builtins",
		"title": "Edge Primitives"
	},
	"dynamics": {
		"slug": "dynamics",
		"category": "builtins",
		"title": "Dynamics"
	},
	"compressor": {
		"slug": "dynamics",
		"category": "builtins",
		"title": "Dynamics"
	},
	"noisegate": {
		"slug": "dynamics",
		"category": "builtins",
		"title": "Dynamics"
	},
	"ratio": {
		"slug": "fm-synthesis",
		"category": "builtins",
		"title": "ratio",
		"anchor": "ratio"
	},
	"ceiling": {
		"slug": "dynamics",
		"category": "builtins",
		"title": "Dynamics"
	},
	"compression": {
		"slug": "dynamics",
		"category": "builtins",
		"title": "Dynamics"
	},
	"oscilloscope": {
		"slug": "visualizations",
		"category": "builtins",
		"title": "oscilloscope",
		"anchor": "oscilloscope"
	},
	"triggerlevel": {
		"slug": "oscilloscope",
		"category": "builtins",
		"title": "triggerLevel",
		"anchor": "triggerlevel"
	},
	"triggeredge": {
		"slug": "oscilloscope",
		"category": "builtins",
		"title": "triggerEdge",
		"anchor": "triggeredge"
	},
	"time-domain": {
		"slug": "oscilloscope",
		"category": "builtins",
		"title": "Oscilloscope"
	},
	"display": {
		"slug": "oscilloscope",
		"category": "builtins",
		"title": "Oscilloscope"
	},
	"monitor": {
		"slug": "oscilloscope",
		"category": "builtins",
		"title": "Oscilloscope"
	},
	"probe": {
		"slug": "oscilloscope",
		"category": "builtins",
		"title": "Oscilloscope"
	},
	"gm": {
		"slug": "soundfonts",
		"category": "builtins",
		"title": "gm",
		"anchor": "gm"
	},
	"preset": {
		"slug": "soundfonts",
		"category": "builtins",
		"title": "preset",
		"anchor": "preset"
	},
	"gain staging": {
		"slug": "soundfonts",
		"category": "builtins",
		"title": "Gain staging",
		"anchor": "gain-staging"
	},
	"sf2": {
		"slug": "soundfonts",
		"category": "builtins",
		"title": "SoundFonts"
	},
	"sf3": {
		"slug": "soundfonts",
		"category": "builtins",
		"title": "SoundFonts"
	},
	"general-midi": {
		"slug": "soundfonts",
		"category": "builtins",
		"title": "SoundFonts"
	},
	"fluidsynth": {
		"slug": "soundfonts",
		"category": "builtins",
		"title": "SoundFonts"
	},
	"timgm6mb": {
		"slug": "soundfonts",
		"category": "builtins",
		"title": "SoundFonts"
	},
	"fluidr3": {
		"slug": "soundfonts",
		"category": "builtins",
		"title": "SoundFonts"
	},
	"musescore": {
		"slug": "soundfonts",
		"category": "builtins",
		"title": "SoundFonts"
	},
	"sync": {
		"slug": "timelines",
		"category": "builtins",
		"title": "sync",
		"anchor": "sync"
	},
	"scheduled": {
		"slug": "timelines",
		"category": "builtins",
		"title": "scheduled",
		"anchor": "scheduled"
	},
	"curve-notation": {
		"slug": "timelines",
		"category": "builtins",
		"title": "Timelines"
	},
	"breakpoints": {
		"slug": "timelines",
		"category": "builtins",
		"title": "Timelines"
	},
	"parameter": {
		"slug": "timelines",
		"category": "builtins",
		"title": "Timelines"
	},
	"waterfall": {
		"slug": "visualizations",
		"category": "builtins",
		"title": "waterfall",
		"anchor": "waterfall"
	},
	"gradient": {
		"slug": "waterfall",
		"category": "builtins",
		"title": "gradient",
		"anchor": "gradient"
	},
	"magma": {
		"slug": "waterfall",
		"category": "builtins",
		"title": "magma",
		"anchor": "magma"
	},
	"viridis": {
		"slug": "waterfall",
		"category": "builtins",
		"title": "viridis",
		"anchor": "viridis"
	},
	"inferno": {
		"slug": "waterfall",
		"category": "builtins",
		"title": "inferno",
		"anchor": "inferno"
	},
	"thermal": {
		"slug": "waterfall",
		"category": "builtins",
		"title": "thermal",
		"anchor": "thermal"
	},
	"grayscale": {
		"slug": "waterfall",
		"category": "builtins",
		"title": "grayscale",
		"anchor": "grayscale"
	},
	"angle": {
		"slug": "waterfall",
		"category": "builtins",
		"title": "angle",
		"anchor": "angle"
	},
	"spectrogram": {
		"slug": "waterfall",
		"category": "builtins",
		"title": "Waterfall"
	},
	"fft": {
		"slug": "spectrum",
		"category": "builtins",
		"title": "fft",
		"anchor": "fft"
	},
	"time-frequency": {
		"slug": "waterfall",
		"category": "builtins",
		"title": "Waterfall"
	},
	"scrolling": {
		"slug": "waterfall",
		"category": "builtins",
		"title": "Waterfall"
	},
	"mindb": {
		"slug": "spectrum",
		"category": "builtins",
		"title": "minDb",
		"anchor": "mindb"
	},
	"maxdb": {
		"slug": "spectrum",
		"category": "builtins",
		"title": "maxDb",
		"anchor": "maxdb"
	},
	"spectrum": {
		"slug": "visualizations",
		"category": "builtins",
		"title": "spectrum",
		"anchor": "spectrum"
	},
	"logscale": {
		"slug": "spectrum",
		"category": "builtins",
		"title": "logScale",
		"anchor": "logscale"
	},
	"analyzer": {
		"slug": "spectrum",
		"category": "builtins",
		"title": "Spectrum Analyzer"
	},
	"frequency-domain": {
		"slug": "spectrum",
		"category": "builtins",
		"title": "Spectrum Analyzer"
	},
	"filled": {
		"slug": "waveform",
		"category": "builtins",
		"title": "filled",
		"anchor": "filled"
	},
	"line": {
		"slug": "waveform",
		"category": "builtins",
		"title": "Waveform"
	},
	"room": {
		"slug": "reverbs",
		"category": "builtins",
		"title": "Reverbs"
	},
	"plate": {
		"slug": "reverbs",
		"category": "builtins",
		"title": "Reverbs"
	},
	"space": {
		"slug": "reverbs",
		"category": "builtins",
		"title": "Reverbs"
	},
	"damping": {
		"slug": "reverbs",
		"category": "builtins",
		"title": "Reverbs"
	},
	"carrier": {
		"slug": "fm-synthesis",
		"category": "builtins",
		"title": "carrier",
		"anchor": "carrier"
	},
	"modulator": {
		"slug": "fm-synthesis",
		"category": "builtins",
		"title": "modulator",
		"anchor": "modulator"
	},
	"sideband": {
		"slug": "fm-synthesis",
		"category": "builtins",
		"title": "sideband",
		"anchor": "sideband"
	},
	"harmonic": {
		"slug": "fm-synthesis",
		"category": "builtins",
		"title": "harmonic",
		"anchor": "harmonic"
	},
	"fm": {
		"slug": "fm-synthesis",
		"category": "builtins",
		"title": "FM Synthesis"
	},
	"device": {
		"slug": "midi",
		"category": "builtins",
		"title": "MIDI Input"
	},
	"velocity": {
		"slug": "midi",
		"category": "builtins",
		"title": "MIDI Input"
	},
	"freq": {
		"slug": "midi",
		"category": "builtins",
		"title": "MIDI Input"
	},
	"trig": {
		"slug": "midi",
		"category": "builtins",
		"title": "MIDI Input"
	},
	"tempo": {
		"slug": "midi",
		"category": "builtins",
		"title": "MIDI Input"
	},
	"mpk": {
		"slug": "midi",
		"category": "builtins",
		"title": "MIDI Input"
	},
	"held-note": {
		"slug": "midi",
		"category": "builtins",
		"title": "MIDI Input"
	},
	"hotswap": {
		"slug": "midi",
		"category": "builtins",
		"title": "MIDI Input"
	},
	"contributing": {
		"slug": "DOCUMENTATION_GUIDE",
		"category": "concepts",
		"title": "Documentation Guide"
	},
	"documentation": {
		"slug": "DOCUMENTATION_GUIDE",
		"category": "concepts",
		"title": "Documentation Guide"
	},
	"guide": {
		"slug": "DOCUMENTATION_GUIDE",
		"category": "concepts",
		"title": "Documentation Guide"
	},
	"standards": {
		"slug": "DOCUMENTATION_GUIDE",
		"category": "concepts",
		"title": "Documentation Guide"
	}
};

export const previews: Record<string, string> = {
	"runtime-controls": "Akkado patches can declare named UI controls that the web IDE turns into live inputs — sliders, momentary buttons, toggles, and dropdowns. Move...",
	"record-as-options": "When a builtin needs more parameters than fit comfortably in positional slots, akkado uses a record literal as the last positional argument. Call...",
	"effect-parameters": "Every effect builtin in akkado — delays, reverbs, modulation, comb, filters, distortion, dynamics — exposes the same two mix parameters at the end...",
	"glide-and-interpolation": "Pattern fields like  and  jump step-wise from one event to the next — they're sample-and-hold buffers.  smooths those jumps over a configurable...",
	"signals": "Akkado has two kinds of audio signals: Mono (one channel) and Stereo (two channels, L and R). Channel count isn't a runtime property — it's a type...",
	"05-testing-progression": "Work through each level in order. Report back which levels work, fail, or have issues.",
	"03-synthesis": "Oscillators and filters give you tone. Envelopes give you notes — they decide when the sound starts and when it dies away.",
	"06-pattern-modulation": "So far patterns have driven note pitches. They're also plain values you can plug into any DSP slot, attach to per-event properties, or combine...",
	"02-filters": "Filters remove or emphasize certain frequencies. A raw saw or square is harmonically dense — bright, buzzy, hard to listen to for long. A filter...",
	"07-midi": "Plug in a keyboard and play through your patch. This tutorial walks from a one-line synth to a full mono lead with CC routing and  file playback.",
	"04-rhythm": "Everything in Akkado syncs to a global clock. The  function creates pulses:",
	"01-hello-sine": "Every Akkado program is a signal flow graph. The smallest one is a sine wave sent to the output:",
	"chords": "Two paths to chordal patterns: the  function with chord-symbol literals (, ), and inline chord brackets in  strings (). For voice leading, the , ,...",
	"microtonal": "Akkado supports microtonal pitch notation through micro-step operators (, , ) and the  function, which selects how those operators map to frequency.",
	"basics": "Mini-notation is a compact syntax for describing musical patterns, inspired by TidalCycles and Strudel.",
	"curve-notation": "Curve notation is an ASCII-art syntax for defining automation curves that compile to Cedar's  opcode breakpoints.",
	"literals": "Patterns can be written as typed string prefixes that disambiguate parse semantics at the literal site:",
	"uri-schemes": "Every asset loaded by nkido — sample banks, SoundFonts, wavetables, single audio files — is identified by a URI. The same scheme syntax works in...",
	"records": "A record is a value that bundles named fields together. Records are immutable: each operation that \"modifies\" a record produces a new record. They...",
	"methods": "Akkado supports method-call syntax for any callable in scope, built-in or user-defined. The form",
	"conditionals": "Signal-rate decision-making: compare signals, combine boolean signals with AND/OR/NOT, and pick between two signals based on a condition. Every...",
	"pipes": "The pipe operator () and hole () define Akkado's signal flow model.",
	"arrays": "Arrays are ordered, fixed-size collections of values. They are the primary way to express parallel signal flows in Akkado: every element of an...",
	"variables": "Variables store values for reuse throughout your patch.",
	"closures": "Closures are anonymous functions that capture their environment. They connect patterns to synthesis.",
	"operators": "Akkado uses operators for arithmetic, comparison, logic, and signal flow.",
	"audio-input": "The  builtin exposes external audio as a signal source (microphone, tab/system audio, or an uploaded file) so any Cedar effect can process it. The...",
	"stereo": "Stereo signal operations. Akkado tracks channel count (Mono vs Stereo) on every signal; every audio DSP op is stereo-native — one instruction...",
	"unison": "Unison takes a single note and multiplies it across N voices that play the same pitch with slightly different detune, stereo pan, and starting...",
	"sequencing": "Timing and sequencing functions create rhythmic patterns, triggers, and automation curves synchronized to the global clock.",
	"delays": "Delay effects create copies of a signal offset in time for echoes, rhythmic effects, and spatial depth.",
	"samples-loading": "How user-supplied audio reaches the sampler at runtime. The  directive declares a bank URI to fetch before the program runs; the IDE also accepts...",
	"polyphony": "Voice allocation for patterns.  runs an instrument function per voice and sums the outputs.  and  are single-voice variants with different...",
	"filters": "Filters shape the frequency content of signals by attenuating or boosting certain frequencies.",
	"midi-cc": "is a compile-time directive that maps an incoming MIDI controller onto an existing  slot. There is no audio-thread work and no extra opcode — the...",
	"distortion": "Distortion effects add harmonic content by clipping, saturating, or otherwise mangling signals.",
	"utility": "Utility functions for common audio tasks like output, MIDI conversion, and signal processing helpers.",
	"envelopes": "Envelopes shape the amplitude or other parameters of a sound over time. They respond to gates (sustained signals) or triggers (momentary pulses).",
	"modulation": "Modulation effects use time-varying delays to add movement and spatial width to sounds.",
	"pianoroll": "A pattern-event visualizer that draws notes as rectangles on a pitch-time grid. It sits in the signal chain as a pass-through.",
	"math": "Mathematical operations for signal processing and control logic.",
	"samplers": "Samplers play recorded audio. The common path is a sample pattern like , which triggers events from the loaded sample bank. nkido ships with a...",
	"oscillators": "Oscillators are the primary sound sources in synthesis. The  function is the unified interface for all oscillator types.",
	"state": "State cells let you persist a single floating-point value across audio blocks from inside a closure. They are the building block for writing your...",
	"edge": "Edge primitives detect transitions in trigger / control signals and accumulate counts. All four variants share one backing opcode () for cache...",
	"dynamics": "Dynamics processors control the volume envelope of signals, reducing dynamic range or removing unwanted quiet sections.",
	"oscilloscope": "A time-domain visualizer that draws the signal as a waveform with trigger stabilization. It sits in the signal chain as a pass-through, so audio...",
	"soundfonts": "SoundFonts (.sf2 / .sf3) are bundled instrument banks, usually General MIDI piano, strings, brass, drums. The  builtin plays a pattern through a...",
	"timelines": "Breakpoint automation envelopes synced to the clock. Use  to define smooth parameter curves with arbitrary shapes: slower than an  and more...",
	"waterfall": "A scrolling spectrogram visualizer: time on one axis, frequency on the other, color for amplitude. It sits in the chain as a pass-through, so...",
	"spectrum": "A frequency-domain visualizer that runs an FFT on the signal. It sits in the chain as a pass-through, so audio flows through unchanged.",
	"waveform": "A time-domain envelope visualizer that draws the min/max amplitude of the signal over time. It sits in the chain as a pass-through, so audio flows...",
	"reverbs": "Reverbs simulate acoustic spaces by generating many delayed, filtered reflections. Each algorithm has its own character.",
	"fm-synthesis": "Frequency modulation (FM) synthesizes complex timbres by modulating the frequency of one oscillator (the carrier) with the output of another (the...",
	"visualizations": "Inline visualizations render directly in the editor. Each visualization is a pass-through node in the signal chain: audio flows through unchanged.",
	"midi": "exposes runtime MIDI events the same way  exposes baked pattern events. Drop it into the same pipe stages —  for polyphony, or  for monophonic...",
	"DOCUMENTATION_GUIDE": "This guide outlines standards and practices for writing NKIDO documentation."
};
