// AUTO-GENERATED by scripts/build-welcome-patches.ts. Do not edit by hand.
// Edit the source .akk files in web/static/patches/welcome/ and re-run
// `bun run build:welcome` (also runs as part of `bun run build`).

export const WELCOME_PATCHES: readonly string[] = [
	`// Sine + vibrato: the smallest possible Akkado patch. A 5 Hz LFO
// modulates the carrier frequency by a few hertz. Swap \`sine\` for
// \`saw\`, \`tri\`, \`sqr\`, or \`noise\` to hear other waveforms.

bpm = 120

vibrato = sine( 5) * 3
sine( 440 + vibrato) * 0.3 |> out(@)
`,
	`// Saw + filter sweep: a slow LFO drags the lowpass cutoff up and
// down for classic "wah" tone-shaping. Move \`0.15\` (Hz) to sweep
// faster; raise the \`1.8\` resonance to make the filter sing.

bpm = 120

cutoff = sine( 0.15) * 1200 + 1600
saw(110) * 0.3
    |> lp(@, cutoff, 1.8)
    |> out(@)
`,
	`// Pulse-width modulation: a square whose duty cycle wobbles under
// a slow sine. The duty swings between ~10% and 90%, giving the
// tone a hollow, chorused, vintage-synth character.

bpm = 110

pw = sine( 0.25) * 0.4 + 0.5
sqr_pwm(110, pw) * 0.25
    |> lp(@, 2400)
    |> out(@)
`,
	`// Amplitude modulation: multiplying two sines creates sum-and-
// difference frequencies. Audio-rate modulation produces metallic,
// bell-like sidebands. Try non-integer ratios for inharmonic tones.

bpm = 100

carrier = sine( 440)
mod = sine( 207)
(carrier * mod * 0.25)
    |> reverb(@, ..{dry: .7, wet: .3}) 
    |> out(@)
`,
	`// 2-operator FM stab: a sine carrier reads a sine modulator on its
// frequency input. The modulator's AR envelope drops the FM index
// over time, so the attack is bright and the tail decays to a clean
// sine. The basis of every DX7 Rhodes patch.

bpm = 100

trig = trigger(1)
mod_env = ar(trig, 0.001, 0.7)
mod = sine( 220) * mod_env * 800
sine( 220 + mod) * ar(trig, 0.005, 1.4) * 0.3
    |> reverb(@, 0.5, 0.5, ..{dry: 0.7, wet: 0.3})
    |> out(@)
`,
	`// Wind through trees: broadband noise filtered by a breathing
// lowpass. The slow LFO modulates the cutoff like gusts of air.
// Drop the highpass or move the rates for different weather.

bpm = 100

breath = sine( 0.18) * 600 + 1000
noise() * 0.3
    |> lp(@, breath, 2.0)
    |> hp(@, 200)
    |> out(@)
`,
	`// Four-on-the-floor: the house staple: kick on every quarter, claps
// on the off-beats, hats on every eighth.

bpm = 128

s"bd bd bd bd" <>
s"~ cp" <>
s"hh*2" *.7 <>
`,
	`// Nested mini-notation drum groove: square brackets subdivide a
// beat and \`<>\` cycles between alternatives once per bar. 
// multiply the "speed" of what is in front of *

bpm = 110

s"bd bd sd [bd <sd [rim rim]>]"
    |> out(@)

s"<hh ~ hh hh ~ hh ~ <hh oh>>*2"
    |> out(@ * 0.5)`,
	`// Euclidean rhythm: \`euclid(hits, steps)\` spreads N hits as evenly
// as possible over M steps. (3,8) is the tresillo found in Cuban,
// West African, and bluegrass music. Try (5,8) or (7,16).

bpm = 110

s"bd ~ ~ ~" |> out(@)

sine( 55) * ar(euclid(3, 8), 0.005, 0.4) * 0.7
    |> saturate(@, 3)
    |> lp(@, 500)
    |> out(@)
`,
	`// Acid bass: a saw through a screaming Moog ladder filter with an
// envelope-modulated cutoff. The classic Roland TB-303 squelch.
// Drag the cutoff slider while it plays.

bpm = 130

env = (trig) -> ar(trig, 0.001, 0.2)
cutoff = param("cutoff", 600, 200, 4000)

n"a2 a3 c3 a2 e3 a2 g3 c3".fast(4)       
    |> saw(@freq/2) * env(@trig) 
    |> moog(@, cutoff + env(trigger(1)) * 800, 3.2, _, 1.6)
    |> saturate(@)
    |> out(@)`,
	`// Polyphonic chord pad: \`chord("...")\` emits one event per chord
// (up to 3 voices each), and \`poly()\` allocates a voice per active
// note. Each voice has its own gate, frequency, and velocity.

bpm = 80

fn pad ({freq, gate, vel}) ->
    saw(freq) 
    * adsr(gate, 0.3, 0.4, 0.8, 0.8) 
    * vel * 0.1
        |> lp(@, 1400)

chord("Cmaj7 Am7 Dm7 <Gm5 G7>")
    |> poly(@, pad)
    |> reverb(@, 0.7, 0.5, ..{dry:0.7,wet:.25})
    |> out(@)`,
	`// Plucky arp: an distilled blues scale stepped one note per beat
// The ar envelope gives each note a percussive pluck; the
// lowpass softens the highs; the delay adds rhythmic echoes.

bpm = 120


n"a3 c4 d#4 e4 g4 e4 d#4 c4"
    |> tri( @freq) * ar(@trig, 0.001, 0.25) * 0.4
    |> lp(@, 2400)
    |> delay(@, 0.375, 0.4)
    |> out(@)
`,
	`// Reverb drone: root, fifth, and octave saws held continuously 
// with stereo panning and drowned in a massive reverb. 

bpm = 60

saw(110).pan(0.5) + saw(110 * 1.007).pan(-0.5) + saw(165).pan(-0.2) + saw(220).pan(0.2)
    |> reverb(@ * 0.04, 0.93, 0.5, 0.3)
    |> out(@)
`,
	`// True stereo ping-pong delay: \`pingpong()\` is the dedicated stereo
// delay opcode; echoes bounce between left and right channels. The
// mono source widens into stereo as the feedback decays.

bpm = 110

n"e4 ~ ~ b3 ~ ~ g4 ~"
  |> tri( @freq) * ar(@trig, 0.001, 0.3) * 0.4
  |> pingpong(stereo(@, 0), 0.5,0.5)
  |> out(@)
`,
	`// Chorus Saw lead: thickened lead that occupies both stereo channels.

bpm = 110

n"c2 eb2 g2 bb2 c3 bb2 g2 eb2".fast(2)
    |> saw(@freq) + tri(@freq*4) * ar(@trig, 0.005, 0.18) * 0.4
    |> lp(@, 2400)
    |> chorus(@, 0.6, 0.9, 40) 
    |> out(@)`,
	`// Snare roll buildup: a 16-step pattern accelerates the snare hits
// across the bar, climaxing on the downbeat. 

bpm = 120

s"sd ~ sd ~ sd sd ~ sd [sd sd] sd [sd sd] sd [sd sd sd sd] sd ~ <bd cp>" * .7  <>

s"bd ~ ~ ~" <>`,
	`// Polyrhythm: 3 against 4. Square brackets divide a beat evenly,
// so \`[rim*3]\` fits three rims in the same time that \`[hh*4]\` fits four hats. 

bpm = 60

s"[rim*3] [rim*2]" <>
s"[hh*4]  [hh*2]" *.7 <>
`,
	`// Generative texture: slow LFOs at incommensurate rates modulate
// frequency and filter cutoff. Nothing repeats exactly, but the
// contour drifts inside a comfortable musical range.

bpm = 80

slow1 = sine( 0.073) * 200 + 220
slow2 = tri( 0.041) * 1200 + 1800
slow3 = sine(.0923) + 1

  saw_pwm(slow1*sine(55 + slow3 * 12) , slow3/2) * 0.12 
    |> lp(@, slow2, 1.4)    
    |> reverb(@, 0.8, 0.6, ..{dry:0.5, wet: 0.2}) 
    |> limiter(@, -1)
    |> out(@)`,
	`// Arpeggio + dotted-eighth delay: a four-note arpeggio fed into a
// long-feedback delay. Using \`spb\` Seconds Per Beat to set the delay time.

bpm = 120

n"c4 e4 g4 b4"
    |> tri( @freq) * ar(@trig, 0.001, 0.18) * 0.4
    |> lp(@, 3000)
    |> delay(@, spb*1.333, 0.55, ..{wet: 0.75})
    |> out(@)
`,
	`// 31-tone equal temperament: \`tune("31edo", ...)\` makes the \`^\`
// and \`v\` operators step by ~38.7 cents (one 31-tone step). You can
// reach quarter-tones, neutral thirds, and intervals that live
// between the semitones: building blocks of raga and maqam scales.

bpm = 90

n"a3 a^3 a^^3 b3 c^4 dv4 d^4 e4"
    |> tune("31edo", @)
    |> tri( @freq) * ar(@trig, 0.005, 0.4) * 0.3
    |> lp(@, 1800)
    |> reverb(@, 0.7, 0.5) 
    |> out(@)
`
];
