// AUTO-GENERATED by scripts/build-welcome-patches.ts. Do not edit by hand.
// Edit the source .akk files in web/static/patches/welcome/ and re-run
// `bun run build:welcome` (also runs as part of `bun run build`).

export const WELCOME_PATCHES: readonly string[] = [
	`// Sine + vibrato — the smallest possible Akkado patch. A 5 Hz LFO
// modulates the carrier frequency by a few hertz. Swap \`"sin"\` for
// \`"saw"\`, \`"tri"\`, \`"sqr"\`, or \`"noise"\` to hear other waveforms.

bpm = 120

vibrato = osc("sin", 5) * 3
osc("sin", 440 + vibrato) * 0.3 |> out(@)
`,
	`// Saw + filter sweep — a slow LFO drags the lowpass cutoff up and
// down for classic "wah" tone-shaping. Move \`0.15\` (Hz) to sweep
// faster; raise the \`1.8\` resonance to make the filter sing.

bpm = 120

cutoff = osc("sin", 0.15) * 1200 + 1600
osc("saw", 110) * 0.3
    |> lp(@, cutoff, 1.8)
    |> out(@)
`,
	`// Pulse-width modulation — a square whose duty cycle wobbles under
// a slow sine. The duty swings between ~10% and 90%, giving the
// tone a hollow, chorused, vintage-synth character.

bpm = 110

pw = osc("sin", 0.25) * 0.4 + 0.5
sqr_pwm(110, pw) * 0.25
    |> lp(@, 2400)
    |> out(@)
`,
	`// Amplitude modulation — multiplying two sines creates sum-and-
// difference frequencies. Audio-rate modulation produces metallic,
// bell-like sidebands. Try non-integer ratios for inharmonic tones.

bpm = 100

carrier = osc("sin", 440)
mod = osc("sin", 207)
(carrier * mod * 0.25)
    |> @ * 0.7 + freeverb(@, 0.75, 0.5) * 0.3
    |> out(@)
`,
	`// 2-operator FM stab — a sine carrier reads a sine modulator on its
// frequency input. The modulator's AR envelope drops the FM index
// over time, so the attack is bright and the tail decays to a clean
// sine. The basis of every DX7 Rhodes patch.

bpm = 100

trig = trigger(1)
mod_env = ar(trig, 0.001, 0.7)
mod = osc("sin", 220) * mod_env * 800
osc("sin", 220 + mod) * ar(trig, 0.005, 1.4) * 0.3
    |> @ + freeverb(@, 0.5, 0.5) * 0.3
    |> out(@)
`,
	`// Wind through trees — broadband noise filtered by a breathing
// lowpass. The slow LFO modulates the cutoff like gusts of air.
// Drop the highpass or move the rates for different weather.

bpm = 100

breath = osc("sin", 0.18) * 600 + 1000
noise() * 0.3
    |> lp(@, breath, 2.0)
    |> hp(@, 200)
    |> out(@)
`,
	`// Four-on-the-floor — the house staple: kick on every quarter, claps
// on the off-beats, hats on every eighth. Each space-separated token
// is one slot in the bar; \`~\` is a rest.

bpm = 124

s"bd bd bd bd" |> out(@)
s"~ cp ~ cp" |> out(@)
s"hh hh hh hh hh hh hh hh" |> out(@ * 0.5)
`,
	`// Nested mini-notation drum groove — square brackets subdivide a
// beat, commas stack hits in parallel, and \`<>\` cycles between
// alternatives once per bar. Read the pattern aloud to hear it.

bpm = 110

s"bd [bd ~] sd [bd <sd hh>]"
    |> out(@)

s"hh ~ hh hh ~ hh ~ <hh oh>"
    |> out(@ * 0.5)
`,
	`// Euclidean rhythm — \`euclid(hits, steps)\` spreads N hits as evenly
// as possible over M steps. (3,8) is the tresillo found in Cuban,
// West African, and bluegrass music. Try (5,8) or (7,16).

bpm = 110

s"bd ~ ~ ~" |> out(@)

osc("sin", 55) * ar(euclid(3, 8), 0.005, 0.4) * 0.7
    |> saturate(@, 3)
    |> lp(@, 500)
    |> out(@)
`,
	`// Acid bass — a saw through a screaming Moog ladder filter with an
// envelope-modulated cutoff. The classic Roland TB-303 squelch.
// Drag the cutoff slider while it plays.

bpm = 130

env = ar(trigger(4), 0.001, 0.18)
cutoff = param("cutoff", 600, 200, 4000)

n"a2 a3 c3 a2 e3 a2 g3 c3"
    |> osc("saw", @freq) * 0.5
    |> moog(@, cutoff + env * 2400, 3.2, _, 1.6)
    |> out(@)
`,
	`// Polyphonic chord pad — \`chord("...")\` emits one event per chord
// (up to 3 voices each), and \`poly()\` allocates a voice per active
// note. Each voice has its own gate, frequency, and velocity.

bpm = 80

pad = (freq, gate, vel) ->
    osc("saw", freq) * adsr(gate, 0.3, 0.4, 0.8, 0.8) * vel * 0.1
        |> lp(@, 1400)

chord("Cmaj7 Am7 Dm7 G7")
    |> poly(@, pad)
    |> @ * 0.7 + freeverb(@, 0.7, 0.5) * 0.25
    |> out(@)
`,
	`// Pentatonic arp — an A-minor pentatonic scale stepped one note per
// 16th. The AR envelope gives each note a percussive pluck; the
// lowpass softens the highs; the delay adds rhythmic echoes.

bpm = 120

n"a3 c4 d4 e4 g4 e4 d4 c4"
    |> osc("tri", @freq) * ar(@trig, 0.001, 0.25) * 0.4
    |> lp(@, 2400)
    |> @ + delay(@, 0.375, 0.4) * 0.35
    |> out(@)
`,
	`// Reverb drone — root, fifth, and octave saws held continuously and
// drowned in a massive reverb. No envelope, no pattern: the drone
// rings out for as long as you let it.

bpm = 60

drone = osc("saw", 110) + osc("saw", 110 * 1.005) + osc("saw", 165) + osc("saw", 220)

drone * 0.04
    |> @ * 0.6 + freeverb(@, 0.93, 0.4) * 0.5
    |> out(@)
`,
	`// True stereo ping-pong delay — \`pingpong()\` is the dedicated stereo
// delay opcode; echoes bounce between left and right channels. The
// mono source widens into stereo as the feedback decays.

bpm = 110

src = n"e4 ~ ~ b3 ~ ~ g4 ~"
    |> osc("tri", @freq) * ar(@trig, 0.001, 0.3) * 0.4

src + pingpong(src, src, 0.375, 0.6) * 0.7 |> out(@)
`,
	`// Chorus + saw lead — \`chorus()\` outputs 100% wet, so we mix dry
// and wet manually (\`dry * 0.4 + chorus(dry, ...) * 0.6\`) for a
// thickened lead that occupies both stereo channels.

bpm = 110

dry = n"c4 eb4 g4 bb4 c5 bb4 g4 eb4"
    |> osc("saw", @freq) * ar(@trig, 0.005, 0.18) * 0.4
    |> lp(@, 2400)

dry * 0.4 + chorus(dry, 0.6, 0.5) * 0.6 |> out(@)
`,
	`// Snare roll buildup — a 16-step pattern accelerates the snare hits
// across the bar, climaxing on the downbeat. \`<bd cp>\` alternates
// the kick and clap each cycle for an extra surprise.

bpm = 120

s"sd ~ sd ~ sd sd ~ sd [sd sd] sd [sd sd] sd [sd sd sd sd] sd ~ <bd cp>"
    |> out(@ * 0.7)

s"bd ~ ~ ~ bd ~ ~ ~"
    |> out(@)
`,
	`// Polyrhythm — 3 against 4. Square brackets divide a beat evenly,
// so \`[bd*3]\` fits three kicks in the same time that \`[hh*4]\` fits
// four hats. Tap your foot and try to track both layers at once.

bpm = 96

s"[bd*3] [bd*3]" |> out(@)
s"[hh*4] [hh*4]" |> out(@ * 0.5)
`,
	`// Generative texture — slow LFOs at incommensurate rates modulate
// frequency and filter cutoff. Nothing repeats exactly, but the
// contour drifts inside a comfortable musical range.

bpm = 80

slow1 = osc("sin", 0.073) * 200 + 220
slow2 = osc("tri", 0.041) * 1200 + 1800

osc("saw", slow1) * 0.12
    |> lp(@, slow2, 1.4)
    |> @ * 0.5 + freeverb(@, 0.8, 0.6) * 0.25
    |> limiter(@, -1)
    |> out(@)
`,
	`// Arpeggio + dotted-eighth delay — a four-note arpeggio fed into a
// long-feedback delay. The dotted-eighth (\`0.375 s\` at 120 BPM) is
// the famous "U2 / The Edge" rhythmic echo trick.

bpm = 120

n"c4 e4 g4 b4"
    |> osc("tri", @freq) * ar(@trig, 0.001, 0.18) * 0.4
    |> lp(@, 3000)
    |> @ + delay(@, 0.375, 0.55) * 0.7
    |> out(@)
`,
	`// 31-tone equal temperament — \`tune("31edo", ...)\` makes the \`^\`
// and \`v\` operators step by ~38.7 cents (one 31-tone step). You can
// reach quarter-tones, neutral thirds, and intervals that live
// between the semitones — building blocks of raga and maqam scales.

bpm = 90

n"a3 a^3 a^^3 b3 c^4 d4 d^4 e4"
    |> tune("31edo", @)
    |> osc("tri", @freq) * ar(@trig, 0.005, 0.4) * 0.3
    |> lp(@, 1800)
    |> @ + freeverb(@, 0.7, 0.5) * 0.4
    |> out(@)
`
];
