/**
 * Build script: bundle web/static/patches/welcome/*.akk into a single TS
 * module so the drafts store can synchronously pick a random welcome
 * patch for first-load and every new tab.
 *
 * Output: web/src/lib/welcome-patches.generated.ts
 *
 * Run with: bun scripts/build-welcome-patches.ts
 */

import { readdir, readFile, writeFile } from 'fs/promises';
import { join } from 'path';

const WELCOME_DIR = join(import.meta.dir, '../static/patches/welcome');
const OUTPUT_FILE = join(import.meta.dir, '../src/lib/welcome-patches.generated.ts');

function escapeTemplate(s: string): string {
	return s.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');
}

async function build() {
	const entries = await readdir(WELCOME_DIR, { withFileTypes: true });
	const files = entries
		.filter((e) => e.isFile() && e.name.endsWith('.akk'))
		.map((e) => e.name)
		.sort();

	const bodies: string[] = [];
	for (const name of files) {
		const raw = await readFile(join(WELCOME_DIR, name), 'utf-8');
		bodies.push(raw);
	}

	const literals = bodies.map((b) => '\t`' + escapeTemplate(b) + '`').join(',\n');

	const out =
		'// AUTO-GENERATED by scripts/build-welcome-patches.ts. Do not edit by hand.\n' +
		'// Edit the source .akk files in web/static/patches/welcome/ and re-run\n' +
		'// `bun run build:welcome` (also runs as part of `bun run build`).\n' +
		'\n' +
		'export const WELCOME_PATCHES: readonly string[] = [\n' +
		literals +
		'\n];\n';

	await writeFile(OUTPUT_FILE, out, 'utf-8');
	console.log(`[welcome] wrote ${files.length} patches -> ${OUTPUT_FILE}`);
}

build().catch((e) => {
	console.error('[welcome] build failed:', e);
	process.exit(1);
});
