/**
 * Tidal Drum Machines catalog
 *
 * Loads the committed `catalog.json` (generated by
 * `scripts/generate-tdm-catalog.sh`) and registers every drum machine as a
 * known/lazy bank. Audio is never bundled — each sample streams from the
 * pinned `raw.githubusercontent.com` URL on demand and is cached in
 * IndexedDB by the file loader.
 */

import { bankRegistry } from './bank-registry';
import { fileCache, cacheKeyFromUrl } from '$lib/io/file-cache';

/** One drum machine: its directory prefix and sound-code → variant paths. */
export interface CatalogMachine {
	name: string;
	path: string; // e.g. "RolandTR808/" — relative to the catalog base
	sounds: Map<string, string[]>; // sound code → variant paths (un-encoded)
}

/** Raw shape of `catalog.json` as produced by the generator. */
interface RawCatalog {
	_base: string;
	_commit?: string;
	banks: Record<string, Record<string, string[] | string>>;
}

const CATALOG_URL = '/samples/tidal-drum-machines/catalog.json';

let catalogBase = '';
let catalogCommit = '';
const machines = new Map<string, CatalogMachine>();
let loadPromise: Promise<boolean> | null = null;

/** Percent-encode a relative path, preserving `/` (filenames may have spaces). */
function encodePath(path: string): string {
	return path.split('/').map(encodeURIComponent).join('/');
}

/**
 * Fetch and register the drum-machine catalog. Idempotent — repeat calls
 * return the same memoised promise. Resolves `false` (without throwing) when
 * the catalog cannot be loaded, so `.bank()` simply falls back to the
 * existing unknown-bank behavior.
 */
export function ensureCatalogLoaded(): Promise<boolean> {
	if (loadPromise) return loadPromise;
	loadPromise = (async () => {
		try {
			const res = await fetch(CATALOG_URL);
			if (!res.ok) throw new Error(`HTTP ${res.status}`);
			const cat = (await res.json()) as RawCatalog;
			catalogBase = cat._base;
			catalogCommit = cat._commit ?? '';

			for (const [name, bank] of Object.entries(cat.banks)) {
				const path = (bank._path as string) || `${name}/`;
				const sounds = new Map<string, string[]>();
				const encodedSamples = new Map<string, string[]>();
				for (const [code, value] of Object.entries(bank)) {
					if (code === '_path') continue;
					const variants = Array.isArray(value) ? value : [value as string];
					sounds.set(code, variants);
					encodedSamples.set(code, variants.map(encodePath));
				}
				machines.set(name, { name, path, sounds });
				// Register as a known/lazy bank: no samples are fetched here,
				// only the metadata + variant-path map. Per-sample fetch is
				// deferred to ensureBankSampleLoaded(). baseUrl pins the URLs
				// to the upstream commit SHA via the catalog `_base`.
				bankRegistry.registerCatalogBank(
					name,
					catalogBase + encodePath(path),
					encodedSamples
				);
			}
			console.log(`[BankCatalog] Registered ${machines.size} drum machines`);
			return true;
		} catch (err) {
			console.warn('[BankCatalog] drum-machine catalog unavailable:', err);
			return false;
		}
	})();
	return loadPromise;
}

/** True once the catalog is loaded and `name` is one of its machines. */
export function hasCatalogBank(name: string): boolean {
	return machines.has(name);
}

/** All catalog machines, sorted by name (for the Files-panel browser). */
export function getCatalogMachines(): CatalogMachine[] {
	return Array.from(machines.values()).sort((a, b) => a.name.localeCompare(b.name));
}

/** A single catalog machine by name, or undefined. */
export function getCatalogMachine(name: string): CatalogMachine | undefined {
	return machines.get(name);
}

/** Upstream commit SHA the catalog URLs are pinned to. */
export function getCatalogCommit(): string {
	return catalogCommit;
}

/**
 * Build the pinned GitHub raw URL for one catalog sample, or `null` when the
 * bank/sound is unknown. Variant index wraps (Strudel behavior).
 */
export function resolveCatalogSample(
	bank: string,
	name: string,
	variant: number
): string | null {
	const machine = machines.get(bank);
	if (!machine) return null;
	const variants = machine.sounds.get(name);
	if (!variants || variants.length === 0) return null;
	let idx = variant % variants.length;
	if (idx < 0) idx += variants.length;
	return catalogBase + encodePath(machine.path + variants[idx]);
}

/** Every sample URL of one machine — used to prefetch a whole kit. */
export function catalogMachineUrls(name: string): string[] {
	const machine = machines.get(name);
	if (!machine) return [];
	const urls: string[] = [];
	for (const variants of machine.sounds.values()) {
		for (const rel of variants) {
			urls.push(catalogBase + encodePath(machine.path + rel));
		}
	}
	return urls;
}

/**
 * Prefetch every sample of one machine into the IndexedDB cache as *pinned*
 * entries (exempt from LRU eviction), so the kit plays offline afterwards.
 * Reports progress per file. Failures are counted, not thrown — a partial
 * prefetch still pins what it managed to fetch.
 */
export async function prefetchCatalogMachine(
	name: string,
	onProgress?: (done: number, total: number) => void
): Promise<{ ok: number; failed: number }> {
	const urls = catalogMachineUrls(name);
	let ok = 0;
	let failed = 0;
	for (let i = 0; i < urls.length; i++) {
		const url = urls[i];
		const key = cacheKeyFromUrl(url);
		try {
			const existing = await fileCache.get(key);
			if (existing) {
				// Already cached (perhaps unpinned) — re-store pinned.
				await fileCache.set(key, existing, { pinned: true });
			} else {
				const res = await fetch(url);
				if (!res.ok) throw new Error(`HTTP ${res.status}`);
				const data = await res.arrayBuffer();
				await fileCache.set(key, data, { pinned: true });
			}
			ok++;
		} catch (err) {
			console.warn(`[BankCatalog] prefetch failed: ${url}`, err);
			failed++;
		}
		onProgress?.(i + 1, urls.length);
	}
	return { ok, failed };
}
