// AUTO-GENERATED FILE — DO NOT EDIT.
// Generated by web/scripts/build-state-init-codec.ts
// To regenerate, run: cd web && bun run build:state-init-codec
//
// Wire-format validator for the state-init buffers produced by the C++ packer
// in akkado/include/akkado/state_init_buffer.hpp (PRD §5). This is a DECODER
// only — the worker packs production data in C++/WASM, never here. The decoder
// + size constants are cross-checked against real C++-packed bytes by
// web/tests/state-init-codec.test.ts, which fails if the wire format ever
// drifts from this generated description.

export const WIRE_VERSION = 2;
export const MAGIC_STATE_INITS = 0x494E4954;
export const MAGIC_MIDI_SOURCES = 0x4D494449;

// Byte sizes of the structs the wire format embeds via raw memcpy. Pinned in
// C++ via static_assert; any change there changes these and must bump
// WIRE_VERSION.
export const EVENT_SIZE = 240;
export const BREAKPOINT_SIZE = 12;
export const BLOCK_ENTRY_SIZE = 12;
// kind:u8 + pad[3] + state_id:u32 + payload_size:u32
export const RECORD_HEADER_SIZE = 12;
// magic:u32 + version:u16 + record_count:u16
export const BUFFER_HEADER_SIZE = 8;

export enum RecordKind {
  StateInit = 0,
  SequenceSampleMapping = 1,
  ScalarSampleMapping = 2,
}

export enum StateInitType {
  Timeline = 1,
  SequenceProgram = 2,
  PolyAlloc = 3,
  ExtendedParams = 4,
  SoundfontEvents = 5,
  ForeachAlloc = 6,
  EventTransform = 7,
  RateScale = 8,
  Reorder = 9,
  Fanout = 10,
}

export interface SequenceSummary {
  duration: number;
  mode: number;
  stepsPerCycle: number;
  numEvents: number;
}

export interface StateInitRecord {
  kind: RecordKind;
  stateId: number;
  payloadSize: number;
  /** present when kind === RecordKind.StateInit */
  type?: StateInitType;
  /** present for StateInitType.SequenceProgram */
  cycleLength?: number;
  isSamplePattern?: boolean;
  totalEvents?: number;
  numSequences?: number;
  sequences?: SequenceSummary[];
}

export interface DecodedStateInits {
  magic: number;
  version: number;
  recordCount: number;
  records: StateInitRecord[];
  /** total bytes consumed by the walk; equals buf.byteLength iff layout matches */
  bytesConsumed: number;
}

export interface MidiSourceRecord {
  stateId: number;
  kind: number;
  channelFilter: number;
  loop: boolean;
  tempoMode: number;
  name: string;
}

export interface DecodedMidiSources {
  magic: number;
  version: number;
  recordCount: number;
  records: MidiSourceRecord[];
  bytesConsumed: number;
}

/**
 * Decode a stateInitsBuf (§5.1–5.3). Walks every record using the on-wire
 * payload_size, and for SequenceProgram records steps over events using
 * EVENT_SIZE — so a wrong EVENT_SIZE makes the per-sequence walk overrun the
 * record's declared payload_size, which the caller can detect.
 */
export function decodeStateInits(buf: Uint8Array): DecodedStateInits {
  const dv = new DataView(buf.buffer, buf.byteOffset, buf.byteLength);
  if (buf.byteLength < BUFFER_HEADER_SIZE) {
    throw new Error("stateInitsBuf shorter than header");
  }
  const magic = dv.getUint32(0, true);
  const version = dv.getUint16(4, true);
  const recordCount = dv.getUint16(6, true);

  const records: StateInitRecord[] = [];
  let off = BUFFER_HEADER_SIZE;
  for (let r = 0; r < recordCount; r++) {
    if (off + RECORD_HEADER_SIZE > buf.byteLength) {
      throw new Error(`record ${r} header overruns buffer`);
    }
    const kind = dv.getUint8(off) as RecordKind;
    const stateId = dv.getUint32(off + 4, true);
    const payloadSize = dv.getUint32(off + 8, true);
    const payloadStart = off + RECORD_HEADER_SIZE;
    const payloadEnd = payloadStart + payloadSize;
    if (payloadEnd > buf.byteLength) {
      throw new Error(`record ${r} payload overruns buffer`);
    }

    const rec: StateInitRecord = { kind, stateId, payloadSize };

    if (kind === RecordKind.StateInit) {
      // Payload starts with type:u8 + pad[3].
      const type = dv.getUint8(payloadStart) as StateInitType;
      rec.type = type;
      let p = payloadStart + 4;
      if (type === StateInitType.SequenceProgram) {
        rec.cycleLength = dv.getFloat32(p, true);
        p += 4;
        rec.isSamplePattern = dv.getUint8(p) !== 0;
        p += 4; // u8 + pad[3]
        rec.totalEvents = dv.getUint32(p, true);
        p += 4;
        const numSequences = dv.getUint32(p, true);
        p += 4;
        rec.numSequences = numSequences;
        const sequences: SequenceSummary[] = [];
        for (let s = 0; s < numSequences; s++) {
          const duration = dv.getFloat32(p, true);
          p += 4;
          const mode = dv.getUint8(p);
          p += 4; // u8 + pad[3]
          const stepsPerCycle = dv.getFloat32(p, true);
          p += 4;
          const numEvents = dv.getUint32(p, true);
          p += 4;
          p += numEvents * EVENT_SIZE; // skip the memcpy'd cedar::Event[]
          sequences.push({ duration, mode, stepsPerCycle, numEvents });
        }
        rec.sequences = sequences;
        if (p !== payloadEnd) {
          throw new Error(
            `SequenceProgram record ${r} walked to ${p}, expected ${payloadEnd} ` +
              `(EVENT_SIZE/layout drift?)`
          );
        }
      }
    }

    records.push(rec);
    off = payloadEnd;
  }

  return { magic, version, recordCount, records, bytesConsumed: off };
}

/** Decode a midiSourcesBuf (§5.6). */
export function decodeMidiSources(buf: Uint8Array): DecodedMidiSources {
  const dv = new DataView(buf.buffer, buf.byteOffset, buf.byteLength);
  if (buf.byteLength < BUFFER_HEADER_SIZE) {
    throw new Error("midiSourcesBuf shorter than header");
  }
  const magic = dv.getUint32(0, true);
  const version = dv.getUint16(4, true);
  const recordCount = dv.getUint16(6, true);

  const decoder = new TextDecoder();
  const records: MidiSourceRecord[] = [];
  let off = BUFFER_HEADER_SIZE;
  for (let r = 0; r < recordCount; r++) {
    const stateId = dv.getUint32(off, true);
    const kind = dv.getUint8(off + 4);
    const channelFilter = dv.getUint8(off + 5);
    const loop = dv.getUint8(off + 6) !== 0;
    const tempoMode = dv.getUint8(off + 7);
    const nameLen = dv.getUint16(off + 8, true);
    // off+10..off+12: pad[2]
    const nameStart = off + 12;
    const name = decoder.decode(buf.subarray(nameStart, nameStart + nameLen));
    let next = nameStart + nameLen;
    // Records are padded to a 4-byte boundary by the packer.
    while (next % 4 !== 0) next++;
    records.push({ stateId, kind, channelFilter, loop, tempoMode, name });
    off = next;
  }

  return { magic, version, recordCount, records, bytesConsumed: off };
}
